services:
  database:
    image: postgres:14.18-bookworm
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: user
      POSTGRES_DB: spaceships
    ports:
      - "8001:5432"
  adminer:
    image: adminer:5.3.0-standalone
    restart: always
    ports:
      - "8080:8080"
  server:
    depends_on:
      - database
    user: "node"
    volumes:
      - ./:/usr/src/game
      - /usr/src/game/server/node_modules
    build: server
    ports:
      - "3000:3000"
  build_client:
    user: "node"
    volumes:
      - ./:/usr/src/game
      - /usr/src/game/client/node_modules
    build: client