/*
This file is autogenerated using server/src/tools/MapActions.ts tool.
Do not change it by hand! Instead, rerun generation script.
 */

import {constructAction} from "./ActionConstructors";
import * as Types from "./Types";


export function initGameState(state: Types.GameState) {
    return constructAction(
        'initGameState',
        {state},
        {}  // meta
    );
}


export function playerRebuiltSpaceship(player: Types.PlayerId, newSpaceship: Types.Spaceship, newHand: Types.Card[]) {
    return constructAction(
        'playerRebuiltSpaceship',
        {player, newSpaceship, newHand},
        {}  // meta
    );
}


export function disposeCardsFromPlayerHand(player: Types.PlayerId, indices: number[]) {
    return constructAction(
        'disposeCardsFromPlayerHand',
        {player, indices},
        {}  // meta
    );
}


export function beginFight(attacker: Types.PlayerId, victim: Types.PlayerId) {
    return constructAction(
        'beginFight',
        {attacker, victim},
        {}  // meta
    );
}


export function popCardFromHeap(type: Types.CardType) {
    return constructAction(
        'popCardFromHeap',
        {type},
        {}  // meta
    );
}


export function setCurrentPlayer(player: Types.PlayerId) {
    return constructAction(
        'setCurrentPlayer',
        {player},
        {}  // meta
    );
}


export function changePlayerEnergy(player: Types.PlayerId, delta: number) {
    return constructAction(
        'changePlayerEnergy',
        {player, delta},
        {}  // meta
    );
}


export function returnDiscardsToStack(type: Types.CardType, discards: Types.Card[]) {
    return constructAction(
        'returnDiscardsToStack',
        {type, discards},
        {}  // meta
    );
}


export function playerSkipNextTurn(player: Types.PlayerId) {
    return constructAction(
        'playerSkipNextTurn',
        {player},
        {}  // meta
    );
}


export function destructSpaceshipModules(player: Types.PlayerId, positions: Types.Vector2[], destructedCardsDestiny: Types.CardDestination, detachedCardsDestiny: Types.CardDestination) {
    return constructAction(
        'destructSpaceshipModules',
        {player, positions, destructedCardsDestiny, detachedCardsDestiny},
        {}  // meta
    );
}


export function pushCardsToStack(type: Types.CardType, cards: Types.Card[]) {
    return constructAction(
        'pushCardsToStack',
        {type, cards},
        {}  // meta
    );
}


export function pushCardsToHand(player: Types.PlayerId, cards: Types.Card[]) {
    return constructAction(
        'pushCardsToHand',
        {player, cards},
        {}  // meta
    );
}


export function changeModuleHealth(player: Types.PlayerId, position: Types.Vector2, delta: number) {
    return constructAction(
        'changeModuleHealth',
        {player, position, delta},
        {}  // meta
    );
}


export function popCardFromPlayerHand(player: Types.PlayerId, index: number) {
    return constructAction(
        'popCardFromPlayerHand',
        {player, index},
        {}  // meta
    );
}


export function deactivateProtectorIfActive(player: Types.PlayerId) {
    return constructAction(
        'deactivateProtectorIfActive',
        {player},
        {}  // meta
    );
}


export function removeSpaceshipModules(player: Types.PlayerId, positions: Types.Vector2[]) {
    return constructAction(
        'removeSpaceshipModules',
        {player, positions},
        {}  // meta
    );
}


export function pushCardsToDiscard(type: Types.CardType, cards: Types.Card[]) {
    return constructAction(
        'pushCardsToDiscard',
        {type, cards},
        {}  // meta
    );
}


export function playerLost(player: Types.PlayerId) {
    return constructAction(
        'playerLost',
        {player},
        {}  // meta
    );
}


export function endFight() {
    return constructAction(
        'endFight',
        {},
        {}  // meta
    );
}


export function activateProtector(player: Types.PlayerId, position: Types.Vector2) {
    return constructAction(
        'activateProtector',
        {player, position},
        {}  // meta
    );
}


export function shiftFightTurnToNextPlayer() {
    return constructAction(
        'shiftFightTurnToNextPlayer',
        {},
        {}  // meta
    );
}


export function playerUseModuleSecondTime(player: Types.PlayerId) {
    return constructAction(
        'playerUseModuleSecondTime',
        {player},
        {}  // meta
    );
}


export function addTimeRecord(player: Types.PlayerId, type: Types.TimeRecordType, time: number) {
    return constructAction(
        'addTimeRecord',
        {player, type, time},
        {}  // meta
    );
}


export function changePlayerTime(player: Types.PlayerId, delta: number) {
    return constructAction(
        'changePlayerTime',
        {player, delta},
        {}  // meta
    );
}


export function insertPause(from: number, to: number) {
    return constructAction(
        'insertPause',
        {from, to},
        {}  // meta
    );
}


export function choosePlayerForAttackRequest(player: Types.PlayerId, reason: Types.AttackReason, required: boolean) {
    return constructAction(
        'choosePlayerForAttackRequest',
        {player, reason, required},
        {}  // meta
    );
}


export function choosePlayerForAttackResponse(victim: Types.PlayerId) {
    return constructAction(
        'choosePlayerForAttackResponse',
        {victim},
        {}  // meta
    );
}


export function rebuildSpaceshipRequest(player: Types.PlayerId) {
    return constructAction(
        'rebuildSpaceshipRequest',
        {player},
        {}  // meta
    );
}


export function rebuildSpaceshipResponse(newSpaceship: { id: Types.ModuleId, position: Types.Vector2, rotation: number }[]) {
    return constructAction(
        'rebuildSpaceshipResponse',
        {newSpaceship},
        {}  // meta
    );
}


export function chooseCardTypeRequest(player: Types.PlayerId) {
    return constructAction(
        'chooseCardTypeRequest',
        {player},
        {}  // meta
    );
}


export function chooseCardTypeResponse(chosenType: Types.CardType) {
    return constructAction(
        'chooseCardTypeResponse',
        {chosenType},
        {}  // meta
    );
}


export function showCardsToPlayersRequest(player: Types.PlayerId, cardsReceiver: Types.PlayerId, cards: Types.Card[]) {
    return constructAction(
        'showCardsToPlayersRequest',
        {player, cardsReceiver, cards},
        {}  // meta
    );
}


export function showCardsToPlayersResponse() {
    return constructAction(
        'showCardsToPlayersResponse',
        {},
        {}  // meta
    );
}


export function drawAdditionalModuleCardRequest(player: Types.PlayerId) {
    return constructAction(
        'drawAdditionalModuleCardRequest',
        {player},
        {}  // meta
    );
}


export function drawAdditionalModuleCardResponse(draw: boolean) {
    return constructAction(
        'drawAdditionalModuleCardResponse',
        {draw},
        {}  // meta
    );
}


export function drawAnotherEventCardRequest(player: Types.PlayerId) {
    return constructAction(
        'drawAnotherEventCardRequest',
        {player},
        {}  // meta
    );
}


export function drawAnotherEventCardResponse(draw: boolean) {
    return constructAction(
        'drawAnotherEventCardResponse',
        {draw},
        {}  // meta
    );
}


export function discardCardsRequest(player: Types.PlayerId) {
    return constructAction(
        'discardCardsRequest',
        {player},
        {}  // meta
    );
}


export function discardCardsResponse(indexes: number[]) {
    return constructAction(
        'discardCardsResponse',
        {indexes},
        {}  // meta
    );
}


export function chooseProtectorRequest(player: Types.PlayerId) {
    return constructAction(
        'chooseProtectorRequest',
        {player},
        {}  // meta
    );
}


export function chooseProtectorResponse(position: Types.Vector2) {
    return constructAction(
        'chooseProtectorResponse',
        {position},
        {}  // meta
    );
}


export function chooseWeaponAndTargetRequest(player: Types.PlayerId, victim: Types.PlayerId) {
    return constructAction(
        'chooseWeaponAndTargetRequest',
        {player, victim},
        {}  // meta
    );
}


export function chooseWeaponAndTargetResponse(targetPosition: Types.Vector2, weaponPosition: Types.Vector2) {
    return constructAction(
        'chooseWeaponAndTargetResponse',
        {targetPosition, weaponPosition},
        {}  // meta
    );
}


export function useModuleSecondTimeRequest(player: Types.PlayerId, moduleType: Types.ModuleType) {
    return constructAction(
        'useModuleSecondTimeRequest',
        {player, moduleType},
        {}  // meta
    );
}


export function useModuleSecondTimeResponse(use: boolean) {
    return constructAction(
        'useModuleSecondTimeResponse',
        {use},
        {}  // meta
    );
}


export function chooseTargetRequest(player: Types.PlayerId, victim: Types.PlayerId) {
    return constructAction(
        'chooseTargetRequest',
        {player, victim},
        {}  // meta
    );
}


export function chooseTargetResponse(position: Types.Vector2) {
    return constructAction(
        'chooseTargetResponse',
        {position},
        {}  // meta
    );
}


export function chooseModuleToRepairRequest(player: Types.PlayerId) {
    return constructAction(
        'chooseModuleToRepairRequest',
        {player},
        {}  // meta
    );
}


export function chooseModuleToRepairResponse(position: Types.Vector2) {
    return constructAction(
        'chooseModuleToRepairResponse',
        {position},
        {}  // meta
    );
}


export function reducerUpdatedState(delta: any) {
    return constructAction(
        'reducerUpdatedState',
        {delta},
        {}  // meta
    );
}


export function showCardsInfo(player: Types.PlayerId, cardsReceiver: Types.PlayerId, cards: Types.Card[]) {
    return constructAction(
        'showCardsInfo',
        {player, cardsReceiver, cards},
        {}  // meta
    );
}


export function sendPlayerLostInfo(player: Types.PlayerId) {
    return constructAction(
        'sendPlayerLostInfo',
        {player},
        {}  // meta
    );
}


export function permuteTopThreeEventCardsRequest(player: Types.PlayerId, cards: Types.EventCard[]) {
    return constructAction(
        'permuteTopThreeEventCardsRequest',
        {player, cards},
        {}  // meta
    );
}


export function permuteTopThreeEventCardsResponse(order: number[]) {
    return constructAction(
        'permuteTopThreeEventCardsResponse',
        {order},
        {}  // meta
    );
}


export function chooseModuleToDestroyRequest(player: Types.PlayerId) {
    return constructAction(
        'chooseModuleToDestroyRequest',
        {player},
        {}  // meta
    );
}


export function chooseModuleToDestroyResponse(position: Types.Vector2) {
    return constructAction(
        'chooseModuleToDestroyResponse',
        {position},
        {}  // meta
    );
}


export function chooseCardsForRepairSpaceshipRequest(player: Types.PlayerId) {
    return constructAction(
        'chooseCardsForRepairSpaceshipRequest',
        {player},
        {}  // meta
    );
}


export function chooseCardsForRepairSpaceshipResponse(indexes: number[]) {
    return constructAction(
        'chooseCardsForRepairSpaceshipResponse',
        {indexes},
        {}  // meta
    );
}


export function chooseModulesToRepairByDiscardedCardsRequest(player: Types.PlayerId, count: number) {
    return constructAction(
        'chooseModulesToRepairByDiscardedCardsRequest',
        {player, count},
        {}  // meta
    );
}


export function chooseModulesToRepairByDiscardedCardsResponse(positions: Types.Vector2[]) {
    return constructAction(
        'chooseModulesToRepairByDiscardedCardsResponse',
        {positions},
        {}  // meta
    );
}


export function chooseSolarPanelsToDestroyRequest(player: Types.PlayerId, count: number) {
    return constructAction(
        'chooseSolarPanelsToDestroyRequest',
        {player, count},
        {}  // meta
    );
}


export function chooseSolarPanelsToDestroyResponse(positions: Types.Vector2[]) {
    return constructAction(
        'chooseSolarPanelsToDestroyResponse',
        {positions},
        {}  // meta
    );
}


export function chooseModuleToRepairByDiceRequest(player: Types.PlayerId, amount: number) {
    return constructAction(
        'chooseModuleToRepairByDiceRequest',
        {player, amount},
        {}  // meta
    );
}


export function chooseModuleToRepairByDiceResponse(position: Types.Vector2) {
    return constructAction(
        'chooseModuleToRepairByDiceResponse',
        {position},
        {}  // meta
    );
}


export function chooseCardsToDiscardAndTakeAnotherRequest(player: Types.PlayerId) {
    return constructAction(
        'chooseCardsToDiscardAndTakeAnotherRequest',
        {player},
        {}  // meta
    );
}


export function chooseCardsToDiscardAndTakeAnotherResponse(indexes: number[]) {
    return constructAction(
        'chooseCardsToDiscardAndTakeAnotherResponse',
        {indexes},
        {}  // meta
    );
}


export function chooseModuleToMoveDamageRequest(player: Types.PlayerId, reason: Types.MoveDamageReason) {
    return constructAction(
        'chooseModuleToMoveDamageRequest',
        {player, reason},
        {}  // meta
    );
}


export function chooseModuleToMoveDamageResponse(move: { from: Types.Vector2, to: Types.Vector2 }) {
    return constructAction(
        'chooseModuleToMoveDamageResponse',
        {move},
        {}  // meta
    );
}


export function chooseModuleToDamageByDiceRequest(player: Types.PlayerId, damage: number) {
    return constructAction(
        'chooseModuleToDamageByDiceRequest',
        {player, damage},
        {}  // meta
    );
}


export function chooseModuleToDamageByDiceResponse(info: { victimId: Types.PlayerId, victimModulePosition: Types.Vector2 }) {
    return constructAction(
        'chooseModuleToDamageByDiceResponse',
        {info},
        {}  // meta
    );
}


export function choosePlayerToStealCardRequest(player: Types.PlayerId, options: Types.PlayerId[]) {
    return constructAction(
        'choosePlayerToStealCardRequest',
        {player, options},
        {}  // meta
    );
}


export function choosePlayerToStealCardResponse(target: Types.PlayerId) {
    return constructAction(
        'choosePlayerToStealCardResponse',
        {target},
        {}  // meta
    );
}


export function chooseCardToStealRequest(player: Types.PlayerId, cards: Types.Card[]) {
    return constructAction(
        'chooseCardToStealRequest',
        {player, cards},
        {}  // meta
    );
}


export function chooseCardToStealResponse(chosenCardIndex: number) {
    return constructAction(
        'chooseCardToStealResponse',
        {chosenCardIndex},
        {}  // meta
    );
}


export function useEventCardToDealDamageRequest(player: Types.PlayerId) {
    return constructAction(
        'useEventCardToDealDamageRequest',
        {player},
        {}  // meta
    );
}


export function useEventCardToDealDamageResponse(useEventCard: boolean) {
    return constructAction(
        'useEventCardToDealDamageResponse',
        {useEventCard},
        {}  // meta
    );
}


export function chooseModuleToDamageByEventCardRequest(player: Types.PlayerId, victim: Types.PlayerId) {
    return constructAction(
        'chooseModuleToDamageByEventCardRequest',
        {player, victim},
        {}  // meta
    );
}


export function chooseModuleToDamageByEventCardResponse(position: Types.Vector2) {
    return constructAction(
        'chooseModuleToDamageByEventCardResponse',
        {position},
        {}  // meta
    );
}


export function tryToRunawayRequest(player: Types.PlayerId, type: Types.RunawayType) {
    return constructAction(
        'tryToRunawayRequest',
        {player, type},
        {}  // meta
    );
}


export function tryToRunawayResponse(willRunaway: boolean) {
    return constructAction(
        'tryToRunawayResponse',
        {willRunaway},
        {}  // meta
    );
}


export function throwDice(player: Types.PlayerId) {
    return constructAction(
        'throwDice',
        {player},
        {}  // meta
    );
}


export function throwDiceResult(result: number) {
    return constructAction(
        'throwDiceResult',
        {result},
        {}  // meta
    );
}


export function shuffle(length: number) {
    return constructAction(
        'shuffle',
        {length},
        {}  // meta
    );
}


export function shuffleResult(order: number[]) {
    return constructAction(
        'shuffleResult',
        {order},
        {}  // meta
    );
}


export function time() {
    return constructAction(
        'time',
        {},
        {}  // meta
    );
}


export function timeResult(result: number) {
    return constructAction(
        'timeResult',
        {result},
        {}  // meta
    );
}


export function message(text: string, player: Types.PlayerId) {
    return constructAction(
        'message',
        {text, player},
        {}  // meta
    );
}

