/*
This file is autogenerated using server/src/tools/MapActions.ts tool.
Do not change it by hand! Instead, rerun generation script.
 */

import {constructAction} from "./ActionsHelpers";
import * as Types from "./Types";


export function initGameState(state: Types.GameState) {
    return constructAction(
        'initGameState',
        {state},
    );
}


export function playerRebuiltSpaceship(player: Types.PlayerId, newSpaceship: Types.Spaceship, newHand: Types.Card[]) {
    return constructAction(
        'playerRebuiltSpaceship',
        {player, newSpaceship, newHand},
    );
}


export function beginFight(attacker: Types.PlayerId, victim: Types.PlayerId, reason: string) {
    return constructAction(
        'beginFight',
        {attacker, victim},
        {reason}
    );
}


export function popCardFromStack(type: Types.CardType) {
    return constructAction(
        'popCardFromStack',
        {type},
    );
}


export function setCurrentPlayer(player: Types.PlayerId) {
    return constructAction(
        'setCurrentPlayer',
        {player},
    );
}


export function changePlayerEnergy(player: Types.PlayerId, delta: number, reason: string) {
    return constructAction(
        'changePlayerEnergy',
        {player, delta},
        {reason}
    );
}


export function clearDiscard(type: Types.CardType) {
    return constructAction(
        'clearDiscard',
        {type},
    );
}


export function playerSkipNextTurn(player: Types.PlayerId) {
    return constructAction(
        'playerSkipNextTurn',
        {player},
    );
}


export function destructSpaceshipModules(player: Types.PlayerId, positions: Types.Vector2[], destructedCardsDestiny: Types.CardDestination, detachedCardsDestiny: Types.CardDestination) {
    return constructAction(
        'destructSpaceshipModules',
        {player, positions, destructedCardsDestiny, detachedCardsDestiny},
    );
}


export function pushCardsToStack(cards: Types.Card[]) {
    return constructAction(
        'pushCardsToStack',
        {cards},
    );
}


export function pushCardsToHand(player: Types.PlayerId, cards: Types.Card[]) {
    return constructAction(
        'pushCardsToHand',
        {player, cards},
    );
}


export function changeModuleHealth(player: Types.PlayerId, position: Types.Vector2, delta: number, reason: string) {
    return constructAction(
        'changeModuleHealth',
        {player, position, delta},
        {reason}
    );
}


export function popCardsFromHand(player: Types.PlayerId, indexes: number[], reason: string) {
    return constructAction(
        'popCardsFromHand',
        {player, indexes},
        {reason}
    );
}


export function deactivateProtectorIfActive(player: Types.PlayerId) {
    return constructAction(
        'deactivateProtectorIfActive',
        {player},
    );
}


export function removeSpaceshipModules(player: Types.PlayerId, positions: Types.Vector2[]) {
    return constructAction(
        'removeSpaceshipModules',
        {player, positions},
    );
}


export function pushCardsToDiscard(cards: Types.Card[]) {
    return constructAction(
        'pushCardsToDiscard',
        {cards},
    );
}


export function playerLost(player: Types.PlayerId) {
    return constructAction(
        'playerLost',
        {player},
    );
}


export function endFight() {
    return constructAction(
        'endFight',
        {},
    );
}


export function activateProtector(player: Types.PlayerId, position: Types.Vector2) {
    return constructAction(
        'activateProtector',
        {player, position},
    );
}


export function shiftFightTurnToNextPlayer() {
    return constructAction(
        'shiftFightTurnToNextPlayer',
        {},
    );
}


export function playerUseModuleSecondTime(player: Types.PlayerId) {
    return constructAction(
        'playerUseModuleSecondTime',
        {player},
    );
}


export function addTimeRecord(player: Types.PlayerId, type: Types.TimeRecordType, time: number) {
    return constructAction(
        'addTimeRecord',
        {player, type, time},
    );
}


export function changePlayerTime(player: Types.PlayerId, delta: number) {
    return constructAction(
        'changePlayerTime',
        {player, delta},
    );
}


export function insertPause(from: number, to: number) {
    return constructAction(
        'insertPause',
        {from, to},
    );
}


export function choosePlayerForAttackRequest(player: Types.PlayerId, reason: Types.AttackReason, required: boolean) {
    return constructAction(
        'choosePlayerForAttackRequest',
        {player, reason, required},
    );
}


export function choosePlayerForAttackResponse(victim?: Types.PlayerId) {
    return constructAction(
        'choosePlayerForAttackResponse',
        {victim},
    );
}


export function rebuildSpaceshipRequest(player: Types.PlayerId) {
    return constructAction(
        'rebuildSpaceshipRequest',
        {player},
    );
}


export function rebuildSpaceshipResponse(newSpaceship: { id: Types.ModuleId, position: Types.Vector2, rotation: number }[]) {
    return constructAction(
        'rebuildSpaceshipResponse',
        {newSpaceship},
    );
}


export function chooseCardTypeRequest(player: Types.PlayerId) {
    return constructAction(
        'chooseCardTypeRequest',
        {player},
    );
}


export function chooseCardTypeResponse(chosenType: Types.CardType) {
    return constructAction(
        'chooseCardTypeResponse',
        {chosenType},
    );
}


export function showCardsToPlayersRequest(player: Types.PlayerId, cardsReceiver: Types.PlayerId, cards: Types.Card[]) {
    return constructAction(
        'showCardsToPlayersRequest',
        {player, cardsReceiver, cards},
    );
}


export function showCardsToPlayersResponse() {
    return constructAction(
        'showCardsToPlayersResponse',
        {},
    );
}


export function drawAdditionalModuleCardRequest(player: Types.PlayerId) {
    return constructAction(
        'drawAdditionalModuleCardRequest',
        {player},
    );
}


export function drawAdditionalModuleCardResponse(draw: boolean) {
    return constructAction(
        'drawAdditionalModuleCardResponse',
        {draw},
    );
}


export function drawAnotherEventCardRequest(player: Types.PlayerId) {
    return constructAction(
        'drawAnotherEventCardRequest',
        {player},
    );
}


export function drawAnotherEventCardResponse(draw: boolean) {
    return constructAction(
        'drawAnotherEventCardResponse',
        {draw},
    );
}


export function discardCardsRequest(player: Types.PlayerId) {
    return constructAction(
        'discardCardsRequest',
        {player},
    );
}


export function discardCardsResponse(indexes: number[]) {
    return constructAction(
        'discardCardsResponse',
        {indexes},
    );
}


export function chooseProtectorRequest(player: Types.PlayerId) {
    return constructAction(
        'chooseProtectorRequest',
        {player},
    );
}


export function chooseProtectorResponse(position?: Types.Vector2) {
    return constructAction(
        'chooseProtectorResponse',
        {position},
    );
}


export function chooseWeaponAndTargetRequest(player: Types.PlayerId, victim: Types.PlayerId) {
    return constructAction(
        'chooseWeaponAndTargetRequest',
        {player, victim},
    );
}


export function chooseWeaponAndTargetResponse(targetPosition: Types.Vector2, weaponPosition: Types.Vector2) {
    return constructAction(
        'chooseWeaponAndTargetResponse',
        {targetPosition, weaponPosition},
    );
}


export function useModuleSecondTimeRequest(player: Types.PlayerId, moduleType: Types.ModuleType) {
    return constructAction(
        'useModuleSecondTimeRequest',
        {player, moduleType},
    );
}


export function useModuleSecondTimeResponse(use: boolean) {
    return constructAction(
        'useModuleSecondTimeResponse',
        {use},
    );
}


export function chooseTargetRequest(player: Types.PlayerId, victim: Types.PlayerId) {
    return constructAction(
        'chooseTargetRequest',
        {player, victim},
    );
}


export function chooseTargetResponse(position: Types.Vector2) {
    return constructAction(
        'chooseTargetResponse',
        {position},
    );
}


export function chooseModuleToRepairRequest(player: Types.PlayerId) {
    return constructAction(
        'chooseModuleToRepairRequest',
        {player},
    );
}


export function chooseModuleToRepairResponse(position?: Types.Vector2) {
    return constructAction(
        'chooseModuleToRepairResponse',
        {position},
    );
}


export function reducerUpdatedState(delta: any) {
    return constructAction(
        'reducerUpdatedState',
        {delta},
    );
}


export function showCardsInfo(player: Types.PlayerId, cardsReceiver: Types.PlayerId, cards: Types.Card[]) {
    return constructAction(
        'showCardsInfo',
        {player, cardsReceiver, cards},
    );
}


export function sendPlayerLostInfo(player: Types.PlayerId) {
    return constructAction(
        'sendPlayerLostInfo',
        {player},
    );
}


export function permuteTopThreeEventCardsRequest(player: Types.PlayerId, cards: Types.EventCard[]) {
    return constructAction(
        'permuteTopThreeEventCardsRequest',
        {player, cards},
    );
}


export function permuteTopThreeEventCardsResponse(order: number[]) {
    return constructAction(
        'permuteTopThreeEventCardsResponse',
        {order},
    );
}


export function chooseModuleToDestroyRequest(player: Types.PlayerId) {
    return constructAction(
        'chooseModuleToDestroyRequest',
        {player},
    );
}


export function chooseModuleToDestroyResponse(position: Types.Vector2) {
    return constructAction(
        'chooseModuleToDestroyResponse',
        {position},
    );
}


export function chooseCardsForRepairSpaceshipRequest(player: Types.PlayerId) {
    return constructAction(
        'chooseCardsForRepairSpaceshipRequest',
        {player},
    );
}


export function chooseCardsForRepairSpaceshipResponse(indexes: number[]) {
    return constructAction(
        'chooseCardsForRepairSpaceshipResponse',
        {indexes},
    );
}


export function chooseModulesToRepairByDiscardedCardsRequest(player: Types.PlayerId, count: number) {
    return constructAction(
        'chooseModulesToRepairByDiscardedCardsRequest',
        {player, count},
    );
}


export function chooseModulesToRepairByDiscardedCardsResponse(positions: Types.Vector2[]) {
    return constructAction(
        'chooseModulesToRepairByDiscardedCardsResponse',
        {positions},
    );
}


export function chooseSolarPanelsToDestroyRequest(player: Types.PlayerId, count: number) {
    return constructAction(
        'chooseSolarPanelsToDestroyRequest',
        {player, count},
    );
}


export function chooseSolarPanelsToDestroyResponse(positions: Types.Vector2[]) {
    return constructAction(
        'chooseSolarPanelsToDestroyResponse',
        {positions},
    );
}


export function chooseModuleToRepairByDiceRequest(player: Types.PlayerId, amount: number) {
    return constructAction(
        'chooseModuleToRepairByDiceRequest',
        {player, amount},
    );
}


export function chooseModuleToRepairByDiceResponse(position?: Types.Vector2) {
    return constructAction(
        'chooseModuleToRepairByDiceResponse',
        {position},
    );
}


export function chooseCardsToDiscardAndTakeAnotherRequest(player: Types.PlayerId) {
    return constructAction(
        'chooseCardsToDiscardAndTakeAnotherRequest',
        {player},
    );
}


export function chooseCardsToDiscardAndTakeAnotherResponse(indexes: number[]) {
    return constructAction(
        'chooseCardsToDiscardAndTakeAnotherResponse',
        {indexes},
    );
}


export function chooseModuleToMoveDamageRequest(player: Types.PlayerId, reason: Types.MoveDamageReason) {
    return constructAction(
        'chooseModuleToMoveDamageRequest',
        {player, reason},
    );
}


export function chooseModuleToMoveDamageResponse(move?: { from: Types.Vector2, to: Types.Vector2 }) {
    return constructAction(
        'chooseModuleToMoveDamageResponse',
        {move},
    );
}


export function chooseModuleToDamageByDiceRequest(player: Types.PlayerId, damage: number) {
    return constructAction(
        'chooseModuleToDamageByDiceRequest',
        {player, damage},
    );
}


export function chooseModuleToDamageByDiceResponse(info?: { victimId: Types.PlayerId, victimModulePosition: Types.Vector2 }) {
    return constructAction(
        'chooseModuleToDamageByDiceResponse',
        {info},
    );
}


export function choosePlayerToStealCardRequest(player: Types.PlayerId, options: Types.PlayerId[]) {
    return constructAction(
        'choosePlayerToStealCardRequest',
        {player, options},
    );
}


export function choosePlayerToStealCardResponse(target: Types.PlayerId) {
    return constructAction(
        'choosePlayerToStealCardResponse',
        {target},
    );
}


export function chooseCardToStealRequest(player: Types.PlayerId, cards: Types.Card[]) {
    return constructAction(
        'chooseCardToStealRequest',
        {player, cards},
    );
}


export function chooseCardToStealResponse(chosenCardIndex: number) {
    return constructAction(
        'chooseCardToStealResponse',
        {chosenCardIndex},
    );
}


export function useEventCardToDealDamageRequest(player: Types.PlayerId) {
    return constructAction(
        'useEventCardToDealDamageRequest',
        {player},
    );
}


export function useEventCardToDealDamageResponse(useEventCard: boolean) {
    return constructAction(
        'useEventCardToDealDamageResponse',
        {useEventCard},
    );
}


export function chooseModuleToDamageByEventCardRequest(player: Types.PlayerId, victim: Types.PlayerId) {
    return constructAction(
        'chooseModuleToDamageByEventCardRequest',
        {player, victim},
    );
}


export function chooseModuleToDamageByEventCardResponse(position: Types.Vector2) {
    return constructAction(
        'chooseModuleToDamageByEventCardResponse',
        {position},
    );
}


export function tryToRunawayRequest(player: Types.PlayerId, type: Types.RunawayType) {
    return constructAction(
        'tryToRunawayRequest',
        {player, type},
    );
}


export function tryToRunawayResponse(willRunaway: boolean) {
    return constructAction(
        'tryToRunawayResponse',
        {willRunaway},
    );
}


export function throwDice(player: Types.PlayerId) {
    return constructAction(
        'throwDice',
        {player},
    );
}


export function throwDiceResult(result: number) {
    return constructAction(
        'throwDiceResult',
        {result},
    );
}


export function shuffle(length: number) {
    return constructAction(
        'shuffle',
        {length},
    );
}


export function shuffleResult(order: number[]) {
    return constructAction(
        'shuffleResult',
        {order},
    );
}


export function time() {
    return constructAction(
        'time',
        {},
    );
}


export function timeResult(result: number) {
    return constructAction(
        'timeResult',
        {result},
    );
}


export function message(player: Types.PlayerId, text: string) {
    return constructAction(
        'message',
        {player, text},
    );
}

