/*
This file is autogenerated using server/src/tools/codegen/Codegen.ts tool.
Do not change it by hand! Instead, rerun generation script.
*/

import {constructAction} from "./ActionsHelpers";
import * as Types from "./Types";


/**
 * @param  state  
 */
export function initGameState(state: Types.GameState) {
    return constructAction(
        'initGameState',
        {state},
    );
}


/**
 * @param  player  
 * @param  newSpaceship  
 * @param  newHand  
 */
export function playerRebuiltSpaceship(player: Types.PlayerId, newSpaceship: Types.Spaceship, newHand: Types.Card[]) {
    return constructAction(
        'playerRebuiltSpaceship',
        {player, newSpaceship, newHand},
    );
}


/**
 * @param  attacker  
 * @param  victim  
 *
 * Мета-параметры события:
* @param  reason  
 */
export function beginFight(attacker: Types.PlayerId, victim: Types.PlayerId, reason: string) {
    return constructAction(
        'beginFight',
        {attacker, victim},
        {reason}
    );
}


/**
 * @param  type  
 */
export function popCardFromStack(type: Types.CardType) {
    return constructAction(
        'popCardFromStack',
        {type},
    );
}


/**
 * @param  player  
 */
export function setCurrentPlayer(player: Types.PlayerId) {
    return constructAction(
        'setCurrentPlayer',
        {player},
    );
}


/**
 * @param  player  
 * @param  delta  
 *
 * Мета-параметры события:
* @param  reason  
 */
export function changePlayerEnergy(player: Types.PlayerId, delta: number, reason: string) {
    return constructAction(
        'changePlayerEnergy',
        {player, delta},
        {reason}
    );
}


/**
 * @param  type  
 */
export function clearDiscard(type: Types.CardType) {
    return constructAction(
        'clearDiscard',
        {type},
    );
}


/**
 * @param  player  
 */
export function playerSkipNextTurn(player: Types.PlayerId) {
    return constructAction(
        'playerSkipNextTurn',
        {player},
    );
}


/**
 * @param  player  
 * @param  positions  
 * @param  destructedCardsDestiny  
 * @param  detachedCardsDestiny  
 */
export function destructSpaceshipModules(player: Types.PlayerId, positions: Types.Vector2[], destructedCardsDestiny: Types.CardDestination, detachedCardsDestiny: Types.CardDestination) {
    return constructAction(
        'destructSpaceshipModules',
        {player, positions, destructedCardsDestiny, detachedCardsDestiny},
    );
}


/**
 * @param  cards  
 */
export function pushCardsToStack(cards: Types.Card[]) {
    return constructAction(
        'pushCardsToStack',
        {cards},
    );
}


/**
 * @param  player  
 * @param  cards  
 */
export function pushCardsToHand(player: Types.PlayerId, cards: Types.Card[]) {
    return constructAction(
        'pushCardsToHand',
        {player, cards},
    );
}


/**
 * @param  player  
 * @param  position  
 * @param  delta  
 *
 * Мета-параметры события:
* @param  reason  
 */
export function changeModuleHealth(player: Types.PlayerId, position: Types.Vector2, delta: number, reason: string) {
    return constructAction(
        'changeModuleHealth',
        {player, position, delta},
        {reason}
    );
}


/**
 * @param  player  
 * @param  indexes  
 *
 * Мета-параметры события:
* @param  reason  
 */
export function popCardsFromHand(player: Types.PlayerId, indexes: number[], reason: string) {
    return constructAction(
        'popCardsFromHand',
        {player, indexes},
        {reason}
    );
}


/**
 * @param  player  
 */
export function deactivateProtectorIfActive(player: Types.PlayerId) {
    return constructAction(
        'deactivateProtectorIfActive',
        {player},
    );
}


/**
 * @param  player  
 * @param  positions  
 */
export function removeSpaceshipModules(player: Types.PlayerId, positions: Types.Vector2[]) {
    return constructAction(
        'removeSpaceshipModules',
        {player, positions},
    );
}


/**
 * @param  cards  
 */
export function pushCardsToDiscard(cards: Types.Card[]) {
    return constructAction(
        'pushCardsToDiscard',
        {cards},
    );
}


/**
 * @param  player  
 */
export function playerLost(player: Types.PlayerId) {
    return constructAction(
        'playerLost',
        {player},
    );
}


/**
 */
export function endFight() {
    return constructAction(
        'endFight',
        {},
    );
}


/**
 * @param  player  
 * @param  position  
 */
export function activateProtector(player: Types.PlayerId, position: Types.Vector2) {
    return constructAction(
        'activateProtector',
        {player, position},
    );
}


/**
 */
export function shiftFightTurnToNextPlayer() {
    return constructAction(
        'shiftFightTurnToNextPlayer',
        {},
    );
}


/**
 * @param  player  
 */
export function playerUseModuleSecondTime(player: Types.PlayerId) {
    return constructAction(
        'playerUseModuleSecondTime',
        {player},
    );
}


/**
 * @param  player  
 * @param  type  
 * @param  time  
 */
export function addTimeRecord(player: Types.PlayerId, type: Types.TimeRecordType, time: number) {
    return constructAction(
        'addTimeRecord',
        {player, type, time},
    );
}


/**
 * @param  player  
 * @param  delta  
 */
export function changePlayerTime(player: Types.PlayerId, delta: number) {
    return constructAction(
        'changePlayerTime',
        {player, delta},
    );
}


/**
 * @param  begin  
 * @param  end  
 */
export function insertPause(begin: number, end: number) {
    return constructAction(
        'insertPause',
        {begin, end},
    );
}


/**
 * Выбор игрока для атаки. Это действие может вызываться в разных ситуациях (в бою, для карточки действия и т.п.)
 * @param  player  
 * @param  reason  
 * @param  required  
 */
export function choosePlayerForAttackRequest(player: Types.PlayerId, reason: Types.AttackReason, required: boolean) {
    return constructAction(
        'choosePlayerForAttackRequest',
        {player, reason, required},
    );
}


/**
 * @param  victim  
 */
export function choosePlayerForAttackResponse(victim?: Types.PlayerId) {
    return constructAction(
        'choosePlayerForAttackResponse',
        {victim},
    );
}


/**
 * Запрос на перестройку корабля. Используется только во время фазы перестройки корабля.
 * @param  player  
 */
export function rebuildSpaceshipRequest(player: Types.PlayerId) {
    return constructAction(
        'rebuildSpaceshipRequest',
        {player},
    );
}


/**
 * @param  newSpaceship  
 */
export function rebuildSpaceshipResponse(newSpaceship: { id: Types.ModuleId, position: Types.Vector2, rotation: number }[]) {
    return constructAction(
        'rebuildSpaceshipResponse',
        {newSpaceship},
    );
}


/**
 * Используется во время фазы вытягивания карт, когда нужно тянуть либо карточку действия, либо карточку строительства
 * @param  player  
 */
export function chooseCardTypeRequest(player: Types.PlayerId) {
    return constructAction(
        'chooseCardTypeRequest',
        {player},
    );
}


/**
 * @param  chosenType  
 */
export function chooseCardTypeResponse(chosenType: Types.CardType) {
    return constructAction(
        'chooseCardTypeResponse',
        {chosenType},
    );
}


/**
 * Отображение карт у пользователя на экране. 
 * Используется, например, когда игрок вытягивает какую-то карточку и нужно её всем показать
 * @param  player  
 * @param  cardsReceiver  
 * @param  cards  
 */
export function showCardsToPlayersRequest(player: Types.PlayerId, cardsReceiver: Types.PlayerId, cards: Types.Card[]) {
    return constructAction(
        'showCardsToPlayersRequest',
        {player, cardsReceiver, cards},
    );
}


/**
 * Используется, чтобы показать, что игрок увидел вытянутые карты и готов продолжать игру
 */
export function showCardsToPlayersResponse() {
    return constructAction(
        'showCardsToPlayersResponse',
        {},
    );
}


/**
 * Используется во время фазы вытягивания карт, 
 * если у игрока командный модуль позволяет тянуть дополнительные карточки строительства.
 * Игрок может использовать эту способность или отказаться от неё.
 * @param  player  
 */
export function drawAdditionalModuleCardRequest(player: Types.PlayerId) {
    return constructAction(
        'drawAdditionalModuleCardRequest',
        {player},
    );
}


/**
 * @param  draw  
 */
export function drawAdditionalModuleCardResponse(draw: boolean) {
    return constructAction(
        'drawAdditionalModuleCardResponse',
        {draw},
    );
}


/**
 * Используется во время фазы вытягивания карт, 
 * если у игрока командный модуль позволяет вытянуть другую карточку действия.
 * Игрок может использовать эту способность или отказаться от неё.
 * @param  player  
 */
export function drawAnotherEventCardRequest(player: Types.PlayerId) {
    return constructAction(
        'drawAnotherEventCardRequest',
        {player},
    );
}


/**
 * @param  draw  
 */
export function drawAnotherEventCardResponse(draw: boolean) {
    return constructAction(
        'drawAnotherEventCardResponse',
        {draw},
    );
}


/**
 * Если у игрока больше n карт на руке в конце хода, то ему приходит это действие, чтобы он их сбросил
 * @param  player  
 */
export function discardCardsRequest(player: Types.PlayerId) {
    return constructAction(
        'discardCardsRequest',
        {player},
    );
}


/**
 * @param  indexes  
 */
export function discardCardsResponse(indexes: number[]) {
    return constructAction(
        'discardCardsResponse',
        {indexes},
    );
}


/**
 * Используется в бою, когда игрок может использовать протектор
 * @param  player  
 */
export function chooseProtectorRequest(player: Types.PlayerId) {
    return constructAction(
        'chooseProtectorRequest',
        {player},
    );
}


/**
 * @param  position  
 */
export function chooseProtectorResponse(position?: Types.Vector2) {
    return constructAction(
        'chooseProtectorResponse',
        {position},
    );
}


/**
 * Используется в бою, когда атакующий может атаковать модуль соперника.
 * @param  player  
 * @param  victim  
 */
export function chooseWeaponAndTargetRequest(player: Types.PlayerId, victim: Types.PlayerId) {
    return constructAction(
        'chooseWeaponAndTargetRequest',
        {player, victim},
    );
}


/**
 * @param  targetPosition  
 * @param  weaponPosition  
 */
export function chooseWeaponAndTargetResponse(targetPosition: Types.Vector2, weaponPosition: Types.Vector2) {
    return constructAction(
        'chooseWeaponAndTargetResponse',
        {targetPosition, weaponPosition},
    );
}


/**
 * Приходит игроку, когда он может использовать модуль второй раз за счёт способности командного модуля.
 * Это может быть в бою (тогда moduleType - это один из типов оружия), 
 * при починке (тогда moduleType - это RepairModule),
 * при нападении (тогда moduleType - это AttackModule)
 * @param  player  
 * @param  moduleType  
 */
export function useModuleSecondTimeRequest(player: Types.PlayerId, moduleType: Types.ModuleType) {
    return constructAction(
        'useModuleSecondTimeRequest',
        {player, moduleType},
    );
}


/**
 * @param  use  
 */
export function useModuleSecondTimeResponse(use: boolean) {
    return constructAction(
        'useModuleSecondTimeResponse',
        {use},
    );
}


/**
 * Если игрок использует оружие второй раз, то ему остаётся выбрать только цель (так как оружие уже фиксированно).
 * Для этого используется это действие.
 * @param  player  
 * @param  victim  
 */
export function chooseTargetRequest(player: Types.PlayerId, victim: Types.PlayerId) {
    return constructAction(
        'chooseTargetRequest',
        {player, victim},
    );
}


/**
 * @param  position  
 */
export function chooseTargetResponse(position: Types.Vector2) {
    return constructAction(
        'chooseTargetResponse',
        {position},
    );
}


/**
 * Используется при починки корабля с помощью ремонтного модуля.
 * @param  player  
 */
export function chooseModuleToRepairRequest(player: Types.PlayerId) {
    return constructAction(
        'chooseModuleToRepairRequest',
        {player},
    );
}


/**
 * @param  position  
 */
export function chooseModuleToRepairResponse(position?: Types.Vector2) {
    return constructAction(
        'chooseModuleToRepairResponse',
        {position},
    );
}


/**
 * Используется, чтобы логировать все изменения состояния игры
 * @param  delta  
 */
export function reducerUpdatedState(delta: any) {
    return constructAction(
        'reducerUpdatedState',
        {delta},
    );
}


/**
 * Показывает карты игроку. Отличие от showCardsToPlayersRequest в том, 
 * что не ожидается подтверждение от игрока - игра продолжается мгновенно после отправки.
 * @param  player  
 * @param  cardsReceiver  
 * @param  cards  
 */
export function showCardsInfo(player: Types.PlayerId, cardsReceiver: Types.PlayerId, cards: Types.Card[]) {
    return constructAction(
        'showCardsInfo',
        {player, cardsReceiver, cards},
    );
}


/**
 * Сообщение о том, что игрок проиграл. 
 * Не ожидает подтверждения от игрока - игра продолжается мгновенно после отправки.
 * @param  player  
 */
export function sendPlayerLostInfo(player: Types.PlayerId) {
    return constructAction(
        'sendPlayerLostInfo',
        {player},
    );
}


/**
 * Используется для карточки действия: 
 * "Положите верхние 3 карточки действия в произвольном порядке"
 * и "Положите верхние 3 карточки действия в произвольном порядке. Возьмите верхнюю из них".
 * @param  player  
 * @param  cards  
 */
export function permuteTopThreeEventCardsRequest(player: Types.PlayerId, cards: Types.EventCard[]) {
    return constructAction(
        'permuteTopThreeEventCardsRequest',
        {player, cards},
    );
}


/**
 * @param  order  
 */
export function permuteTopThreeEventCardsResponse(order: number[]) {
    return constructAction(
        'permuteTopThreeEventCardsResponse',
        {order},
    );
}


/**
 * Используется для карточки действия "Уничтожьте любой модуль вашего корабля на ваш выбор"
 * @param  player  
 */
export function chooseModuleToDestroyRequest(player: Types.PlayerId) {
    return constructAction(
        'chooseModuleToDestroyRequest',
        {player},
    );
}


/**
 * @param  position  
 */
export function chooseModuleToDestroyResponse(position: Types.Vector2) {
    return constructAction(
        'chooseModuleToDestroyResponse',
        {position},
    );
}


/**
 * Используется для карточки действия 
 * "Вы можете, скинув до 2 карт с руки, восстановить по 1 урона с модулей вашего корабля за каждую скинутую карту".
 * @param  player  
 */
export function chooseCardsForRepairSpaceshipRequest(player: Types.PlayerId) {
    return constructAction(
        'chooseCardsForRepairSpaceshipRequest',
        {player},
    );
}


/**
 * @param  indexes  
 */
export function chooseCardsForRepairSpaceshipResponse(indexes: number[]) {
    return constructAction(
        'chooseCardsForRepairSpaceshipResponse',
        {indexes},
    );
}


/**
 * Используется для карточки действия 
 * "Вы можете, скинув до 2 карт с руки, восстановить по 1 урона с модулей вашего корабля за каждую скинутую карту".
 * Сначала посылается событие chooseCardsForRepairSpaceshipRequest. После получения ответа посылается это событие,
 * чтобы выбрать модули, которые нужно починить.
 * @param  player  
 * @param  count  
 */
export function chooseModulesToRepairByDiscardedCardsRequest(player: Types.PlayerId, count: number) {
    return constructAction(
        'chooseModulesToRepairByDiscardedCardsRequest',
        {player, count},
    );
}


/**
 * @param  positions  
 */
export function chooseModulesToRepairByDiscardedCardsResponse(positions: Types.Vector2[]) {
    return constructAction(
        'chooseModulesToRepairByDiscardedCardsResponse',
        {positions},
    );
}


/**
 * Используется для карточки действия "Уничтожьте 2 солнечные батареи вашего корабля". 
 * Если у игрока на корабле меньше 2-х солнечных батарей, то он уничтожает столько, сколько у него есть.
 * @param  player  
 * @param  count  
 */
export function chooseSolarPanelsToDestroyRequest(player: Types.PlayerId, count: number) {
    return constructAction(
        'chooseSolarPanelsToDestroyRequest',
        {player, count},
    );
}


/**
 * @param  positions  
 */
export function chooseSolarPanelsToDestroyResponse(positions: Types.Vector2[]) {
    return constructAction(
        'chooseSolarPanelsToDestroyResponse',
        {positions},
    );
}


/**
 * Используется для карточки действия
 * "Киньте кубик. Можете восстановить один модуль вашего корабля на 1 урон при выпадении ≤4, а иначе - на 2 урона".
 * @param  player  
 * @param  amount  
 */
export function chooseModuleToRepairByDiceRequest(player: Types.PlayerId, amount: number) {
    return constructAction(
        'chooseModuleToRepairByDiceRequest',
        {player, amount},
    );
}


/**
 * @param  position  
 */
export function chooseModuleToRepairByDiceResponse(position?: Types.Vector2) {
    return constructAction(
        'chooseModuleToRepairByDiceResponse',
        {position},
    );
}


/**
 * Используется для карточки действия
 * "Если у вас есть карты на руках, скиньте в сброс до 2 из них на ваш выбор, 
 * а затем возьмите столько же карт строительства".
 * @param  player  
 */
export function chooseCardsToDiscardAndTakeAnotherRequest(player: Types.PlayerId) {
    return constructAction(
        'chooseCardsToDiscardAndTakeAnotherRequest',
        {player},
    );
}


/**
 * @param  indexes  
 */
export function chooseCardsToDiscardAndTakeAnotherResponse(indexes: number[]) {
    return constructAction(
        'chooseCardsToDiscardAndTakeAnotherResponse',
        {indexes},
    );
}


/**
 * Используется либо для карточки действия "Можете перенести 1 урон с одного вашего модуля на другой",
 * либо для способности командного модуля, которая позволяет переносить урон.
 * @param  player  
 * @param  reason  
 */
export function chooseModuleToMoveDamageRequest(player: Types.PlayerId, reason: Types.MoveDamageReason) {
    return constructAction(
        'chooseModuleToMoveDamageRequest',
        {player, reason},
    );
}


/**
 * @param  move  
 */
export function chooseModuleToMoveDamageResponse(move?: { source: Types.Vector2, destination: Types.Vector2 }) {
    return constructAction(
        'chooseModuleToMoveDamageResponse',
        {move},
    );
}


/**
 * Используется для карточки действия
 * "Киньте кубик. Нанесите любому модулю соперника (кроме командного) 1 урон при выпадении ≤4, а иначе - 2 урона".
 * @param  player  
 * @param  damage  
 */
export function chooseModuleToDamageByDiceRequest(player: Types.PlayerId, damage: number) {
    return constructAction(
        'chooseModuleToDamageByDiceRequest',
        {player, damage},
    );
}


/**
 * @param  info  
 */
export function chooseModuleToDamageByDiceResponse(info?: { victimId: Types.PlayerId, victimModulePosition: Types.Vector2 }) {
    return constructAction(
        'chooseModuleToDamageByDiceResponse',
        {info},
    );
}


/**
 * Используется для карточки действия
 * "Выберите любого игрока, у которого на руках есть карточки. Посмотрите его карты и возьмите себе одну из них на ваш выбор".
 * Это действие запрашивает игрока, у которого нужно своровать карточку
 * @param  player  
 * @param  options  
 */
export function choosePlayerToStealCardRequest(player: Types.PlayerId, options: Types.PlayerId[]) {
    return constructAction(
        'choosePlayerToStealCardRequest',
        {player, options},
    );
}


/**
 * @param  target  
 */
export function choosePlayerToStealCardResponse(target: Types.PlayerId) {
    return constructAction(
        'choosePlayerToStealCardResponse',
        {target},
    );
}


/**
 * @param  player  
 * @param  cards  
 */
export function chooseCardToStealRequest(player: Types.PlayerId, cards: Types.Card[]) {
    return constructAction(
        'chooseCardToStealRequest',
        {player, cards},
    );
}


/**
 * @param  chosenCardIndex  
 */
export function chooseCardToStealResponse(chosenCardIndex: number) {
    return constructAction(
        'chooseCardToStealResponse',
        {chosenCardIndex},
    );
}


/**
 * @param  player  
 */
export function useEventCardToDealDamageRequest(player: Types.PlayerId) {
    return constructAction(
        'useEventCardToDealDamageRequest',
        {player},
    );
}


/**
 * @param  useEventCard  
 */
export function useEventCardToDealDamageResponse(useEventCard: boolean) {
    return constructAction(
        'useEventCardToDealDamageResponse',
        {useEventCard},
    );
}


/**
 * @param  player  
 * @param  victim  
 */
export function chooseModuleToDamageByEventCardRequest(player: Types.PlayerId, victim: Types.PlayerId) {
    return constructAction(
        'chooseModuleToDamageByEventCardRequest',
        {player, victim},
    );
}


/**
 * @param  position  
 */
export function chooseModuleToDamageByEventCardResponse(position: Types.Vector2) {
    return constructAction(
        'chooseModuleToDamageByEventCardResponse',
        {position},
    );
}


/**
 * @param  player  
 * @param  type  
 */
export function tryToRunawayRequest(player: Types.PlayerId, type: Types.RunawayType) {
    return constructAction(
        'tryToRunawayRequest',
        {player, type},
    );
}


/**
 * @param  willRunaway  
 */
export function tryToRunawayResponse(willRunaway: boolean) {
    return constructAction(
        'tryToRunawayResponse',
        {willRunaway},
    );
}


/**
 * @param  player  
 */
export function throwDice(player: Types.PlayerId) {
    return constructAction(
        'throwDice',
        {player},
    );
}


/**
 * @param  result  
 */
export function throwDiceResult(result: number) {
    return constructAction(
        'throwDiceResult',
        {result},
    );
}


/**
 * @param  length  
 */
export function shuffle(length: number) {
    return constructAction(
        'shuffle',
        {length},
    );
}


/**
 * @param  order  
 */
export function shuffleResult(order: number[]) {
    return constructAction(
        'shuffleResult',
        {order},
    );
}


/**
 */
export function time() {
    return constructAction(
        'time',
        {},
    );
}


/**
 * @param  result  
 */
export function timeResult(result: number) {
    return constructAction(
        'timeResult',
        {result},
    );
}


/**
 * @param  player  
 * @param  text  
 */
export function message(player: Types.PlayerId, text: string) {
    return constructAction(
        'message',
        {player, text},
    );
}

