/*
This file is autogenerated using server/src/tools/MapActions.ts tool.
Do not change it by hand! Instead, rerun generation script.
 */

export type PlayerId = number;

export type ModuleId = number;

export type Vector2 = {
    x: number,
    y: number,
};

export enum ModuleType {
    MainModule = "MainModule",
    SpaceSolver = "SpaceSolver",
    IonDestroyer = "IonDestroyer",
    QuantumDestabilizer = "QuantumDestabilizer",
    SolarPanel = "SolarPanel",
    NuclearReactor = "NuclearReactor",
    DarkMatterGenerator = "DarkMatterGenerator",
    SmallBattery = "SmallBattery",
    Battery = "Battery",
    SmallQuantumProtector = "SmallQuantumProtector",
    QuantumProtector = "QuantumProtector",
    AttackModule = "AttackModule",
    RepairModule = "RepairModule",
    StructureModule = "StructureModule",
}

export enum EventType {
    PutTopThreeCardsInAnyOrder = "PutTopThreeCardsInAnyOrder",
    PutTopThreeCardsInAnyOrderAndTakeTop = "PutTopThreeCardsInAnyOrderAndTakeTop",
    TakeOneBuildingCard = "TakeOneBuildingCard",
    TakeTwoBuildingCards = "TakeTwoBuildingCards",
    LooseFiveEnergy = "LooseFiveEnergy",
    TakeFiveEnergy = "TakeFiveEnergy",
    SkipNextTurn = "SkipNextTurn",
    LooseAllYourCards = "LooseAllYourCards",
    DestroyAnyModuleOnYourSpaceship = "DestroyAnyModuleOnYourSpaceship",
    DestroyTwoSolarPanelsOnYourSpaceship = "DestroyTwoSolarPanelsOnYourSpaceship",
    AttackRight = "AttackRight",
    AttackLeft = "AttackLeft",
    AttackNextToRight = "AttackNextToRight",
    AttackNextToLeft = "AttackNextToLeft",
    AttackAny = "AttackAny",
    TossDiceAndTakeBuildingCards = "TossDiceAndTakeBuildingCards",
    TossDiceAndDealDamage = "TossDiceAndDealDamage",
    TossDiceAndGetEnergy = "TossDiceAndGetEnergy",
    TossDiceAndRepairYourModule = "TossDiceAndRepairYourModule",
    SaveCardAndThenAttack = "SaveCardAndThenAttack",
    SaveCardAndThenDealDamage = "SaveCardAndThenDealDamage",
    ChoosePlayerAndStealHisCard = "ChoosePlayerAndStealHisCard",
    DiscardCardAndRepairSpaceship = "DiscardCardAndRepairSpaceship",
    MoveDamage = "MoveDamage",
    DiscardCardsAndTakeBuildingCards = "DiscardCardsAndTakeBuildingCards",
}

export enum MainModuleType {
    DrawAnotherEventCard = "DrawAnotherEventCard",
    DrawAdditionalModuleCard = "DrawAdditionalModuleCard",
    MoveDamage = "MoveDamage",
    UseModuleSecondTime = "UseModuleSecondTime",
    AttackOrRunaway = "AttackOrRunaway",
}

export type ModuleCard = {
    id: ModuleId,
    name: string,
    connectors: { top: number, right: number, bottom: number, left: number },
    strength: number,
    capacity: number,
    energyCost: number,
    energyIncrease: number,
    type: ModuleType,
    totalHealth: number,
    health: number,
    x: number,
    y: number,
    rotation: number,
    mainModuleType?: MainModuleType,
};

export type EventCard = {
    type: EventType,
    description: string,
};

export type Card = { module: ModuleCard, cardType: "module" } | { event: EventCard, cardType: "event" };

export enum CardType {
    Module = "Module",
    Event = "Event",
}

export type TimeControlSettings = {
    startTime: number,
    defaultTimeIncrease: number,
    fightTimeIncrease: number,
    loseWhenTimeout: boolean,
};

export type GameSettings = {
    seed: string,
    isPublic: boolean,
    startCardsCount: number,
    mainModuleRunawayEnergyCost: number,
    energyToAttackByMainModule: number,
    energyToMoveDamageByMainModule: number,
    damageMovedByMainModule: number,
    energyToDragAnotherEventCardByMainModule: number,
    energyToDragAdditionalCardByMainModule: number,
    maxCardsOnHand: number,
    diceResultToRunaway: number,
    timeControlSettings?: TimeControlSettings,
};

export type FightState = {
    first: PlayerId,
    second: PlayerId,
    isFirstPlayerTurn: boolean,
    isFightEnded: boolean,
};

export enum TimeRecordType {
    DEFAULT_TURN_STARTED = "DEFAULT_TURN_STARTED",
    DEFAULT_TURN_ENDED = "DEFAULT_TURN_ENDED",
    DEFAULT_TURN_INTERRUPTED = "DEFAULT_TURN_INTERRUPTED",
    DEFAULT_TURN_CONTINUED = "DEFAULT_TURN_CONTINUED",
    FIGHT_TURN_STARTED = "FIGHT_TURN_STARTED",
    FIGHT_TURN_ENDED = "FIGHT_TURN_ENDED",
    PAUSE_STARTED = "PAUSE_STARTED",
    PAUSE_ENDED = "PAUSE_ENDED",
}

export type TimeRecord = {
    type: TimeRecordType,
    playerId: PlayerId,
    time: number,
};

export type Spaceship = {
    modules: ModuleCard[],
    activatedProtector?: Vector2,
};

export type Player = {
    id: PlayerId,
    name: string,
    spaceship: Spaceship,
    hand: Card[],
    energy: number,
    skipNextTurn: boolean,
    usedModuleSecondTimeOnThisTurn: boolean,
    lose: boolean,
    time: number,
};

export type GameState = {
    stack: { module: ModuleCard[], event: EventCard[] },
    discards: { module: ModuleCard[], event: EventCard[] },
    mainModulesStack: ModuleCard[],
    players: Player[],
    currentPlayerId: PlayerId,
    settings: GameSettings,
    timeRecords: TimeRecord[],
    fight?: FightState,
};

export type Message = {
    text: string,
    payload?: any,
};

export enum MoveDamageReason {
    MainModule = "MainModule",
    EventCard = "EventCard",
}

export enum RunawayType {
    Dice = "Dice",
    MainModule = "MainModule",
}

export enum AttackReason {
    MainModule = "MainModule",
    AttackModule = "AttackModule",
    AttackAnyEventCard = "AttackAnyEventCard",
    AttackLaterEventCard = "AttackLaterEventCard",
    UsingAttackModuleSecondTime = "UsingAttackModuleSecondTime",
}

export enum CardDestination {
    hand = "hand",
    discard = "discard",
}