"""
This file is autogenerated using server/src/tools/codegen/Codegen.ts tool.
Do not change it by hand! Instead, rerun generation script.
"""

from __future__ import annotations

from dataclasses import dataclass

import time
import uuid

from core.types import *


@dataclass
class ChoosePlayerForAttackRequestPayload:
    player: PlayerId
    reason: AttackReason
    required: bool


@dataclass
class ChoosePlayerForAttackRequest:
    uuid: str
    time: int
    type: Literal["choosePlayerForAttackRequest"]
    payload: ChoosePlayerForAttackRequestPayload


def choosePlayerForAttackRequest(player: PlayerId, reason: AttackReason, required: bool) \
        -> ChoosePlayerForAttackRequest:
    """
    Выбор игрока для атаки. Это действие может вызываться в разных ситуациях (в бою, для карточки действия и т.п.)
    :param player: 
    :param reason: Причина, по которой нужно выбирать игрока для атаки
    :param required: Обязательно ли нужно выбрать кого-то. Если это значение false, то в ответе можно не отправлять выбранного игрока
    :return: Сконструированное действие
    """

    return ChoosePlayerForAttackRequest(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="choosePlayerForAttackRequest",
        payload=ChoosePlayerForAttackRequestPayload(player, reason, required)
    )


@dataclass
class ChoosePlayerForAttackResponsePayload:
    victim: PlayerId | None


@dataclass
class ChoosePlayerForAttackResponse:
    uuid: str
    time: int
    type: Literal["choosePlayerForAttackResponse"]
    payload: ChoosePlayerForAttackResponsePayload


def choosePlayerForAttackResponse(victim: PlayerId | None) \
        -> ChoosePlayerForAttackResponse:
    """
    :param victim: Выбранный игрок. Может быть undefined, если в запросе required == false
    :return: Сконструированное действие
    """

    return ChoosePlayerForAttackResponse(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="choosePlayerForAttackResponse",
        payload=ChoosePlayerForAttackResponsePayload(victim)
    )


@dataclass
class RebuildSpaceshipRequestPayload:
    player: PlayerId


@dataclass
class RebuildSpaceshipRequest:
    uuid: str
    time: int
    type: Literal["rebuildSpaceshipRequest"]
    payload: RebuildSpaceshipRequestPayload


def rebuildSpaceshipRequest(player: PlayerId) \
        -> RebuildSpaceshipRequest:
    """
    Запрос на перестройку корабля. Используется только во время фазы перестройки корабля.
    :param player: 
    :return: Сконструированное действие
    """

    return RebuildSpaceshipRequest(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="rebuildSpaceshipRequest",
        payload=RebuildSpaceshipRequestPayload(player)
    )


@dataclass
class RebuildSpaceshipResponsePayload:
    newSpaceship: list[RebuildSpaceshipResponseNewSpaceshipElements]


@dataclass
class RebuildSpaceshipResponse:
    uuid: str
    time: int
    type: Literal["rebuildSpaceshipResponse"]
    payload: RebuildSpaceshipResponsePayload


def rebuildSpaceshipResponse(newSpaceship: list[RebuildSpaceshipResponseNewSpaceshipElements]) \
        -> RebuildSpaceshipResponse:
    """
    :param newSpaceship: Информация о модулях в перестроенном корабле
    :return: Сконструированное действие
    """

    return RebuildSpaceshipResponse(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="rebuildSpaceshipResponse",
        payload=RebuildSpaceshipResponsePayload(newSpaceship)
    )


@dataclass
class ChooseCardTypeRequestPayload:
    player: PlayerId


@dataclass
class ChooseCardTypeRequest:
    uuid: str
    time: int
    type: Literal["chooseCardTypeRequest"]
    payload: ChooseCardTypeRequestPayload


def chooseCardTypeRequest(player: PlayerId) \
        -> ChooseCardTypeRequest:
    """
    Используется во время фазы вытягивания карт, когда нужно тянуть либо карточку действия, либо карточку строительства
    :param player: 
    :return: Сконструированное действие
    """

    return ChooseCardTypeRequest(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="chooseCardTypeRequest",
        payload=ChooseCardTypeRequestPayload(player)
    )


@dataclass
class ChooseCardTypeResponsePayload:
    chosenType: CardType


@dataclass
class ChooseCardTypeResponse:
    uuid: str
    time: int
    type: Literal["chooseCardTypeResponse"]
    payload: ChooseCardTypeResponsePayload


def chooseCardTypeResponse(chosenType: CardType) \
        -> ChooseCardTypeResponse:
    """
    :param chosenType: Выбранный тип карты - строительства или действия
    :return: Сконструированное действие
    """

    return ChooseCardTypeResponse(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="chooseCardTypeResponse",
        payload=ChooseCardTypeResponsePayload(chosenType)
    )


@dataclass
class ShowCardsToPlayersRequestPayload:
    player: PlayerId
    cardsReceiver: PlayerId
    cards: list[Card]


@dataclass
class ShowCardsToPlayersRequest:
    uuid: str
    time: int
    type: Literal["showCardsToPlayersRequest"]
    payload: ShowCardsToPlayersRequestPayload


def showCardsToPlayersRequest(player: PlayerId, cardsReceiver: PlayerId, cards: list[Card]) \
        -> ShowCardsToPlayersRequest:
    """
    Отображение карт у пользователя на экране. 
    Используется, например, когда игрок вытягивает какую-то карточку и нужно её всем показать
    :param player: 
    :param cardsReceiver: Игрок, который получил отображаемые карточки
    :param cards: Карточки, которые нужно показать
    :return: Сконструированное действие
    """

    return ShowCardsToPlayersRequest(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="showCardsToPlayersRequest",
        payload=ShowCardsToPlayersRequestPayload(player, cardsReceiver, cards)
    )


@dataclass
class ShowCardsToPlayersResponsePayload:
    pass


@dataclass
class ShowCardsToPlayersResponse:
    uuid: str
    time: int
    type: Literal["showCardsToPlayersResponse"]
    payload: ShowCardsToPlayersResponsePayload


def showCardsToPlayersResponse() \
        -> ShowCardsToPlayersResponse:
    """
    Используется, чтобы показать, что игрок увидел вытянутые карты и готов продолжать игру
    :return: Сконструированное действие
    """

    return ShowCardsToPlayersResponse(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="showCardsToPlayersResponse",
        payload=ShowCardsToPlayersResponsePayload()
    )


@dataclass
class DrawAdditionalModuleCardRequestPayload:
    player: PlayerId


@dataclass
class DrawAdditionalModuleCardRequest:
    uuid: str
    time: int
    type: Literal["drawAdditionalModuleCardRequest"]
    payload: DrawAdditionalModuleCardRequestPayload


def drawAdditionalModuleCardRequest(player: PlayerId) \
        -> DrawAdditionalModuleCardRequest:
    """
    Используется во время фазы вытягивания карт, 
    если у игрока командный модуль позволяет тянуть дополнительные карточки строительства.
    Игрок может использовать эту способность или отказаться от неё.
    :param player: 
    :return: Сконструированное действие
    """

    return DrawAdditionalModuleCardRequest(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="drawAdditionalModuleCardRequest",
        payload=DrawAdditionalModuleCardRequestPayload(player)
    )


@dataclass
class DrawAdditionalModuleCardResponsePayload:
    draw: bool


@dataclass
class DrawAdditionalModuleCardResponse:
    uuid: str
    time: int
    type: Literal["drawAdditionalModuleCardResponse"]
    payload: DrawAdditionalModuleCardResponsePayload


def drawAdditionalModuleCardResponse(draw: bool) \
        -> DrawAdditionalModuleCardResponse:
    """
    :param draw: Хочет ли игрок вытягивать дополнительную карточку строительства с помощью способности командного модуля
    :return: Сконструированное действие
    """

    return DrawAdditionalModuleCardResponse(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="drawAdditionalModuleCardResponse",
        payload=DrawAdditionalModuleCardResponsePayload(draw)
    )


@dataclass
class DrawAnotherEventCardRequestPayload:
    player: PlayerId


@dataclass
class DrawAnotherEventCardRequest:
    uuid: str
    time: int
    type: Literal["drawAnotherEventCardRequest"]
    payload: DrawAnotherEventCardRequestPayload


def drawAnotherEventCardRequest(player: PlayerId) \
        -> DrawAnotherEventCardRequest:
    """
    Используется во время фазы вытягивания карт, 
    если у игрока командный модуль позволяет вытянуть другую карточку действия.
    Игрок может использовать эту способность или отказаться от неё.
    :param player: 
    :return: Сконструированное действие
    """

    return DrawAnotherEventCardRequest(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="drawAnotherEventCardRequest",
        payload=DrawAnotherEventCardRequestPayload(player)
    )


@dataclass
class DrawAnotherEventCardResponsePayload:
    draw: bool


@dataclass
class DrawAnotherEventCardResponse:
    uuid: str
    time: int
    type: Literal["drawAnotherEventCardResponse"]
    payload: DrawAnotherEventCardResponsePayload


def drawAnotherEventCardResponse(draw: bool) \
        -> DrawAnotherEventCardResponse:
    """
    :param draw: Хочет ли игрок вытягивать другую карточку действия с помощью способности командного модуля
    :return: Сконструированное действие
    """

    return DrawAnotherEventCardResponse(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="drawAnotherEventCardResponse",
        payload=DrawAnotherEventCardResponsePayload(draw)
    )


@dataclass
class DiscardCardsRequestPayload:
    player: PlayerId


@dataclass
class DiscardCardsRequest:
    uuid: str
    time: int
    type: Literal["discardCardsRequest"]
    payload: DiscardCardsRequestPayload


def discardCardsRequest(player: PlayerId) \
        -> DiscardCardsRequest:
    """
    Если у игрока больше n карт на руке в конце хода, то ему приходит это действие, чтобы он их сбросил
    :param player: 
    :return: Сконструированное действие
    """

    return DiscardCardsRequest(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="discardCardsRequest",
        payload=DiscardCardsRequestPayload(player)
    )


@dataclass
class DiscardCardsResponsePayload:
    indexes: list[int]


@dataclass
class DiscardCardsResponse:
    uuid: str
    time: int
    type: Literal["discardCardsResponse"]
    payload: DiscardCardsResponsePayload


def discardCardsResponse(indexes: list[int]) \
        -> DiscardCardsResponse:
    """
    :param indexes: Индексы карт на руке, которые нужно сбросить
    :return: Сконструированное действие
    """

    return DiscardCardsResponse(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="discardCardsResponse",
        payload=DiscardCardsResponsePayload(indexes)
    )


@dataclass
class ChooseProtectorRequestPayload:
    player: PlayerId


@dataclass
class ChooseProtectorRequest:
    uuid: str
    time: int
    type: Literal["chooseProtectorRequest"]
    payload: ChooseProtectorRequestPayload


def chooseProtectorRequest(player: PlayerId) \
        -> ChooseProtectorRequest:
    """
    Используется в бою, когда игрок может использовать протектор
    :param player: 
    :return: Сконструированное действие
    """

    return ChooseProtectorRequest(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="chooseProtectorRequest",
        payload=ChooseProtectorRequestPayload(player)
    )


@dataclass
class ChooseProtectorResponsePayload:
    position: Vector2 | None


@dataclass
class ChooseProtectorResponse:
    uuid: str
    time: int
    type: Literal["chooseProtectorResponse"]
    payload: ChooseProtectorResponsePayload


def chooseProtectorResponse(position: Vector2 | None) \
        -> ChooseProtectorResponse:
    """
    :param position: Позиция протектора, который игрок хочет активировать. 
                     Если игрок не хочет активировать протектор, это поле остаётся пустым
    :return: Сконструированное действие
    """

    return ChooseProtectorResponse(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="chooseProtectorResponse",
        payload=ChooseProtectorResponsePayload(position)
    )


@dataclass
class ChooseWeaponAndTargetRequestPayload:
    player: PlayerId
    victim: PlayerId


@dataclass
class ChooseWeaponAndTargetRequest:
    uuid: str
    time: int
    type: Literal["chooseWeaponAndTargetRequest"]
    payload: ChooseWeaponAndTargetRequestPayload


def chooseWeaponAndTargetRequest(player: PlayerId, victim: PlayerId) \
        -> ChooseWeaponAndTargetRequest:
    """
    Используется в бою, когда атакующий может атаковать модуль соперника.
    :param player: 
    :param victim: id игрока, которого нужно атаковать
    :return: Сконструированное действие
    """

    return ChooseWeaponAndTargetRequest(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="chooseWeaponAndTargetRequest",
        payload=ChooseWeaponAndTargetRequestPayload(player, victim)
    )


@dataclass
class ChooseWeaponAndTargetResponsePayload:
    targetPosition: Vector2
    weaponPosition: Vector2


@dataclass
class ChooseWeaponAndTargetResponse:
    uuid: str
    time: int
    type: Literal["chooseWeaponAndTargetResponse"]
    payload: ChooseWeaponAndTargetResponsePayload


def chooseWeaponAndTargetResponse(targetPosition: Vector2, weaponPosition: Vector2) \
        -> ChooseWeaponAndTargetResponse:
    """
    :param targetPosition: Позиция модуля на корабле соперника, который нужно атаковать
    :param weaponPosition: Позиция оружия на корабле атакующего, из которого он будет атаковать
    :return: Сконструированное действие
    """

    return ChooseWeaponAndTargetResponse(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="chooseWeaponAndTargetResponse",
        payload=ChooseWeaponAndTargetResponsePayload(targetPosition, weaponPosition)
    )


@dataclass
class UseModuleSecondTimeRequestPayload:
    player: PlayerId
    moduleType: ModuleType


@dataclass
class UseModuleSecondTimeRequest:
    uuid: str
    time: int
    type: Literal["useModuleSecondTimeRequest"]
    payload: UseModuleSecondTimeRequestPayload


def useModuleSecondTimeRequest(player: PlayerId, moduleType: ModuleType) \
        -> UseModuleSecondTimeRequest:
    """
    Приходит игроку, когда он может использовать модуль второй раз за счёт способности командного модуля.
    Это может быть в бою (тогда moduleType - это один из типов оружия), 
    при починке (тогда moduleType - это RepairModule),
    при нападении (тогда moduleType - это AttackModule)
    :param player: 
    :param moduleType: 
    :return: Сконструированное действие
    """

    return UseModuleSecondTimeRequest(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="useModuleSecondTimeRequest",
        payload=UseModuleSecondTimeRequestPayload(player, moduleType)
    )


@dataclass
class UseModuleSecondTimeResponsePayload:
    use: bool


@dataclass
class UseModuleSecondTimeResponse:
    uuid: str
    time: int
    type: Literal["useModuleSecondTimeResponse"]
    payload: UseModuleSecondTimeResponsePayload


def useModuleSecondTimeResponse(use: bool) \
        -> UseModuleSecondTimeResponse:
    """
    :param use: Хочет ли игрок использовать модуль второй раз за счёт способности командного модуля
    :return: Сконструированное действие
    """

    return UseModuleSecondTimeResponse(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="useModuleSecondTimeResponse",
        payload=UseModuleSecondTimeResponsePayload(use)
    )


@dataclass
class ChooseTargetRequestPayload:
    player: PlayerId
    victim: PlayerId


@dataclass
class ChooseTargetRequest:
    uuid: str
    time: int
    type: Literal["chooseTargetRequest"]
    payload: ChooseTargetRequestPayload


def chooseTargetRequest(player: PlayerId, victim: PlayerId) \
        -> ChooseTargetRequest:
    """
    Если игрок использует оружие второй раз, то ему остаётся выбрать только цель (так как оружие уже фиксированно).
    Для этого используется это действие.
    :param player: 
    :param victim: 
    :return: Сконструированное действие
    """

    return ChooseTargetRequest(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="chooseTargetRequest",
        payload=ChooseTargetRequestPayload(player, victim)
    )


@dataclass
class ChooseTargetResponsePayload:
    position: Vector2


@dataclass
class ChooseTargetResponse:
    uuid: str
    time: int
    type: Literal["chooseTargetResponse"]
    payload: ChooseTargetResponsePayload


def chooseTargetResponse(position: Vector2) \
        -> ChooseTargetResponse:
    """
    :param position: Позиция модуля на корабле соперника, который нужно атаковать
    :return: Сконструированное действие
    """

    return ChooseTargetResponse(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="chooseTargetResponse",
        payload=ChooseTargetResponsePayload(position)
    )


@dataclass
class ChooseModuleToRepairRequestPayload:
    player: PlayerId


@dataclass
class ChooseModuleToRepairRequest:
    uuid: str
    time: int
    type: Literal["chooseModuleToRepairRequest"]
    payload: ChooseModuleToRepairRequestPayload


def chooseModuleToRepairRequest(player: PlayerId) \
        -> ChooseModuleToRepairRequest:
    """
    Используется при починки корабля с помощью ремонтного модуля.
    :param player: 
    :return: Сконструированное действие
    """

    return ChooseModuleToRepairRequest(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="chooseModuleToRepairRequest",
        payload=ChooseModuleToRepairRequestPayload(player)
    )


@dataclass
class ChooseModuleToRepairResponsePayload:
    position: Vector2 | None


@dataclass
class ChooseModuleToRepairResponse:
    uuid: str
    time: int
    type: Literal["chooseModuleToRepairResponse"]
    payload: ChooseModuleToRepairResponsePayload


def chooseModuleToRepairResponse(position: Vector2 | None) \
        -> ChooseModuleToRepairResponse:
    """
    :param position: Позиция модуля на корабле игрока, который он хочет починить с помощью ремонтного модуля.
                     Если игрок не хочет чинить ничего, то этот параметр нужно оставить пустым.
    :return: Сконструированное действие
    """

    return ChooseModuleToRepairResponse(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="chooseModuleToRepairResponse",
        payload=ChooseModuleToRepairResponsePayload(position)
    )


@dataclass
class PermuteTopThreeEventCardsRequestPayload:
    player: PlayerId
    cards: list[EventCard]


@dataclass
class PermuteTopThreeEventCardsRequest:
    uuid: str
    time: int
    type: Literal["permuteTopThreeEventCardsRequest"]
    payload: PermuteTopThreeEventCardsRequestPayload


def permuteTopThreeEventCardsRequest(player: PlayerId, cards: list[EventCard]) \
        -> PermuteTopThreeEventCardsRequest:
    """
    Используется для карточки действия: 
    "Положите верхние 3 карточки действия в произвольном порядке"
    и "Положите верхние 3 карточки действия в произвольном порядке. Возьмите верхнюю из них".
    :param player: 
    :param cards: Карточки, порядок которых нужно выбрать
    :return: Сконструированное действие
    """

    return PermuteTopThreeEventCardsRequest(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="permuteTopThreeEventCardsRequest",
        payload=PermuteTopThreeEventCardsRequestPayload(player, cards)
    )


@dataclass
class PermuteTopThreeEventCardsResponsePayload:
    order: list[int]


@dataclass
class PermuteTopThreeEventCardsResponse:
    uuid: str
    time: int
    type: Literal["permuteTopThreeEventCardsResponse"]
    payload: PermuteTopThreeEventCardsResponsePayload


def permuteTopThreeEventCardsResponse(order: list[int]) \
        -> PermuteTopThreeEventCardsResponse:
    """
    :param order: Новый порядок для верхних 3-x карт. 
                  order[0] - индекс карты из permuteTopThreeEventCardsRequest::cards, которая окажется вверху колоды
                  order[1] - индекс карты из permuteTopThreeEventCardsRequest::cards, которая окажется предпоследней сверху
                  и т.д.
    :return: Сконструированное действие
    """

    return PermuteTopThreeEventCardsResponse(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="permuteTopThreeEventCardsResponse",
        payload=PermuteTopThreeEventCardsResponsePayload(order)
    )


@dataclass
class ChooseModuleToDestroyRequestPayload:
    player: PlayerId


@dataclass
class ChooseModuleToDestroyRequest:
    uuid: str
    time: int
    type: Literal["chooseModuleToDestroyRequest"]
    payload: ChooseModuleToDestroyRequestPayload


def chooseModuleToDestroyRequest(player: PlayerId) \
        -> ChooseModuleToDestroyRequest:
    """
    Используется для карточки действия "Уничтожьте любой модуль вашего корабля на ваш выбор"
    :param player: 
    :return: Сконструированное действие
    """

    return ChooseModuleToDestroyRequest(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="chooseModuleToDestroyRequest",
        payload=ChooseModuleToDestroyRequestPayload(player)
    )


@dataclass
class ChooseModuleToDestroyResponsePayload:
    position: Vector2


@dataclass
class ChooseModuleToDestroyResponse:
    uuid: str
    time: int
    type: Literal["chooseModuleToDestroyResponse"]
    payload: ChooseModuleToDestroyResponsePayload


def chooseModuleToDestroyResponse(position: Vector2) \
        -> ChooseModuleToDestroyResponse:
    """
    :param position: Позиция модуля на корабле игрока, который нужно уничтожить
    :return: Сконструированное действие
    """

    return ChooseModuleToDestroyResponse(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="chooseModuleToDestroyResponse",
        payload=ChooseModuleToDestroyResponsePayload(position)
    )


@dataclass
class ChooseCardsForRepairSpaceshipRequestPayload:
    player: PlayerId


@dataclass
class ChooseCardsForRepairSpaceshipRequest:
    uuid: str
    time: int
    type: Literal["chooseCardsForRepairSpaceshipRequest"]
    payload: ChooseCardsForRepairSpaceshipRequestPayload


def chooseCardsForRepairSpaceshipRequest(player: PlayerId) \
        -> ChooseCardsForRepairSpaceshipRequest:
    """
    Используется для карточки действия 
    "Вы можете, скинув до 2 карт с руки, восстановить по 1 урона с модулей вашего корабля за каждую скинутую карту".
    :param player: 
    :return: Сконструированное действие
    """

    return ChooseCardsForRepairSpaceshipRequest(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="chooseCardsForRepairSpaceshipRequest",
        payload=ChooseCardsForRepairSpaceshipRequestPayload(player)
    )


@dataclass
class ChooseCardsForRepairSpaceshipResponsePayload:
    indexes: list[int]


@dataclass
class ChooseCardsForRepairSpaceshipResponse:
    uuid: str
    time: int
    type: Literal["chooseCardsForRepairSpaceshipResponse"]
    payload: ChooseCardsForRepairSpaceshipResponsePayload


def chooseCardsForRepairSpaceshipResponse(indexes: list[int]) \
        -> ChooseCardsForRepairSpaceshipResponse:
    """
    :param indexes: Индексы карт на руке игрока, которые нужно скинуть (не больше 2)
    :return: Сконструированное действие
    """

    return ChooseCardsForRepairSpaceshipResponse(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="chooseCardsForRepairSpaceshipResponse",
        payload=ChooseCardsForRepairSpaceshipResponsePayload(indexes)
    )


@dataclass
class ChooseModulesToRepairByDiscardedCardsRequestPayload:
    player: PlayerId
    count: int


@dataclass
class ChooseModulesToRepairByDiscardedCardsRequest:
    uuid: str
    time: int
    type: Literal["chooseModulesToRepairByDiscardedCardsRequest"]
    payload: ChooseModulesToRepairByDiscardedCardsRequestPayload


def chooseModulesToRepairByDiscardedCardsRequest(player: PlayerId, count: int) \
        -> ChooseModulesToRepairByDiscardedCardsRequest:
    """
    Используется для карточки действия 
    "Вы можете, скинув до 2 карт с руки, восстановить по 1 урона с модулей вашего корабля за каждую скинутую карту".
    Сначала посылается событие chooseCardsForRepairSpaceshipRequest. После получения ответа посылается это событие,
    чтобы выбрать модули, которые нужно починить.
    :param player: 
    :param count: Количество модулей, которые нужно выбрать для починки. 
                  Совпадает с количеством карт, скинутых в chooseCardsForRepairSpaceshipResponse.
    :return: Сконструированное действие
    """

    return ChooseModulesToRepairByDiscardedCardsRequest(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="chooseModulesToRepairByDiscardedCardsRequest",
        payload=ChooseModulesToRepairByDiscardedCardsRequestPayload(player, count)
    )


@dataclass
class ChooseModulesToRepairByDiscardedCardsResponsePayload:
    positions: list[Vector2]


@dataclass
class ChooseModulesToRepairByDiscardedCardsResponse:
    uuid: str
    time: int
    type: Literal["chooseModulesToRepairByDiscardedCardsResponse"]
    payload: ChooseModulesToRepairByDiscardedCardsResponsePayload


def chooseModulesToRepairByDiscardedCardsResponse(positions: list[Vector2]) \
        -> ChooseModulesToRepairByDiscardedCardsResponse:
    """
    :param positions: Позиции модулей на корабле игрока, которые нужно починить. 
                      Их количество должно совпадать с chooseModulesToRepairByDiscardedCardsRequest::count.
    :return: Сконструированное действие
    """

    return ChooseModulesToRepairByDiscardedCardsResponse(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="chooseModulesToRepairByDiscardedCardsResponse",
        payload=ChooseModulesToRepairByDiscardedCardsResponsePayload(positions)
    )


@dataclass
class ChooseSolarPanelsToDestroyRequestPayload:
    player: PlayerId
    count: int


@dataclass
class ChooseSolarPanelsToDestroyRequest:
    uuid: str
    time: int
    type: Literal["chooseSolarPanelsToDestroyRequest"]
    payload: ChooseSolarPanelsToDestroyRequestPayload


def chooseSolarPanelsToDestroyRequest(player: PlayerId, count: int) \
        -> ChooseSolarPanelsToDestroyRequest:
    """
    Используется для карточки действия "Уничтожьте 2 солнечные батареи вашего корабля". 
    Если у игрока на корабле меньше 2-х солнечных батарей, то он уничтожает столько, сколько у него есть.
    :param player: 
    :param count: Количество солнечных батарей, которые надо уничтожить
    :return: Сконструированное действие
    """

    return ChooseSolarPanelsToDestroyRequest(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="chooseSolarPanelsToDestroyRequest",
        payload=ChooseSolarPanelsToDestroyRequestPayload(player, count)
    )


@dataclass
class ChooseSolarPanelsToDestroyResponsePayload:
    positions: list[Vector2]


@dataclass
class ChooseSolarPanelsToDestroyResponse:
    uuid: str
    time: int
    type: Literal["chooseSolarPanelsToDestroyResponse"]
    payload: ChooseSolarPanelsToDestroyResponsePayload


def chooseSolarPanelsToDestroyResponse(positions: list[Vector2]) \
        -> ChooseSolarPanelsToDestroyResponse:
    """
    :param positions: Позиции солнечных батарей на корабле игрока, которые надо уничтожить.
                      Ровно chooseSolarPanelsToDestroyRequest::count штук.
    :return: Сконструированное действие
    """

    return ChooseSolarPanelsToDestroyResponse(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="chooseSolarPanelsToDestroyResponse",
        payload=ChooseSolarPanelsToDestroyResponsePayload(positions)
    )


@dataclass
class ChooseModuleToRepairByDiceRequestPayload:
    player: PlayerId
    amount: int


@dataclass
class ChooseModuleToRepairByDiceRequest:
    uuid: str
    time: int
    type: Literal["chooseModuleToRepairByDiceRequest"]
    payload: ChooseModuleToRepairByDiceRequestPayload


def chooseModuleToRepairByDiceRequest(player: PlayerId, amount: int) \
        -> ChooseModuleToRepairByDiceRequest:
    """
    Используется для карточки действия
    "Киньте кубик. Можете восстановить один модуль вашего корабля на 1 урон при выпадении ≤4, а иначе - на 2 урона".
    :param player: 
    :param amount: Количество урона, которое можно убрать с модуля. Зависит от результата броска кубика.
    :return: Сконструированное действие
    """

    return ChooseModuleToRepairByDiceRequest(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="chooseModuleToRepairByDiceRequest",
        payload=ChooseModuleToRepairByDiceRequestPayload(player, amount)
    )


@dataclass
class ChooseModuleToRepairByDiceResponsePayload:
    position: Vector2 | None


@dataclass
class ChooseModuleToRepairByDiceResponse:
    uuid: str
    time: int
    type: Literal["chooseModuleToRepairByDiceResponse"]
    payload: ChooseModuleToRepairByDiceResponsePayload


def chooseModuleToRepairByDiceResponse(position: Vector2 | None) \
        -> ChooseModuleToRepairByDiceResponse:
    """
    :param position: Позиция модуля на корабле игрока, который нужно починить.
                     Если игрок не хочет чинить модули, то это поле остаётся пустым.
    :return: Сконструированное действие
    """

    return ChooseModuleToRepairByDiceResponse(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="chooseModuleToRepairByDiceResponse",
        payload=ChooseModuleToRepairByDiceResponsePayload(position)
    )


@dataclass
class ChooseCardsToDiscardAndTakeAnotherRequestPayload:
    player: PlayerId


@dataclass
class ChooseCardsToDiscardAndTakeAnotherRequest:
    uuid: str
    time: int
    type: Literal["chooseCardsToDiscardAndTakeAnotherRequest"]
    payload: ChooseCardsToDiscardAndTakeAnotherRequestPayload


def chooseCardsToDiscardAndTakeAnotherRequest(player: PlayerId) \
        -> ChooseCardsToDiscardAndTakeAnotherRequest:
    """
    Используется для карточки действия
    "Если у вас есть карты на руках, скиньте в сброс до 2 из них на ваш выбор, 
    а затем возьмите столько же карт строительства".
    :param player: 
    :return: Сконструированное действие
    """

    return ChooseCardsToDiscardAndTakeAnotherRequest(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="chooseCardsToDiscardAndTakeAnotherRequest",
        payload=ChooseCardsToDiscardAndTakeAnotherRequestPayload(player)
    )


@dataclass
class ChooseCardsToDiscardAndTakeAnotherResponsePayload:
    indexes: list[int]


@dataclass
class ChooseCardsToDiscardAndTakeAnotherResponse:
    uuid: str
    time: int
    type: Literal["chooseCardsToDiscardAndTakeAnotherResponse"]
    payload: ChooseCardsToDiscardAndTakeAnotherResponsePayload


def chooseCardsToDiscardAndTakeAnotherResponse(indexes: list[int]) \
        -> ChooseCardsToDiscardAndTakeAnotherResponse:
    """
    :param indexes: Индексы модулей на руке игрока, которые нужно скинуть в обмен на карточки строительства (не более 2)
    :return: Сконструированное действие
    """

    return ChooseCardsToDiscardAndTakeAnotherResponse(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="chooseCardsToDiscardAndTakeAnotherResponse",
        payload=ChooseCardsToDiscardAndTakeAnotherResponsePayload(indexes)
    )


@dataclass
class ChooseModuleToMoveDamageRequestPayload:
    player: PlayerId
    reason: MoveDamageReason


@dataclass
class ChooseModuleToMoveDamageRequest:
    uuid: str
    time: int
    type: Literal["chooseModuleToMoveDamageRequest"]
    payload: ChooseModuleToMoveDamageRequestPayload


def chooseModuleToMoveDamageRequest(player: PlayerId, reason: MoveDamageReason) \
        -> ChooseModuleToMoveDamageRequest:
    """
    Используется либо для карточки действия "Можете перенести 1 урон с одного вашего модуля на другой",
    либо для способности командного модуля, которая позволяет переносить урон.
    :param player: 
    :param reason: Причина, по которой игрок переносит урон: карточка действия или командный модуль
    :return: Сконструированное действие
    """

    return ChooseModuleToMoveDamageRequest(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="chooseModuleToMoveDamageRequest",
        payload=ChooseModuleToMoveDamageRequestPayload(player, reason)
    )


@dataclass
class ChooseModuleToMoveDamageResponsePayload:
    move: ChooseModuleToMoveDamageResponseMove | None


@dataclass
class ChooseModuleToMoveDamageResponse:
    uuid: str
    time: int
    type: Literal["chooseModuleToMoveDamageResponse"]
    payload: ChooseModuleToMoveDamageResponsePayload


def chooseModuleToMoveDamageResponse(move: ChooseModuleToMoveDamageResponseMove | None) \
        -> ChooseModuleToMoveDamageResponse:
    """
    :param move: Перемещение урона. source - позиция модуля на корабле игрока, откуда перенести урон,
                 destination - позиция модуля на корабле игрока, на который перенести урон.
                 Если игрок не хочет переносить урон, то это поле остаётся пустым.
    :return: Сконструированное действие
    """

    return ChooseModuleToMoveDamageResponse(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="chooseModuleToMoveDamageResponse",
        payload=ChooseModuleToMoveDamageResponsePayload(move)
    )


@dataclass
class ChooseModuleToDamageByDiceRequestPayload:
    player: PlayerId
    damage: int


@dataclass
class ChooseModuleToDamageByDiceRequest:
    uuid: str
    time: int
    type: Literal["chooseModuleToDamageByDiceRequest"]
    payload: ChooseModuleToDamageByDiceRequestPayload


def chooseModuleToDamageByDiceRequest(player: PlayerId, damage: int) \
        -> ChooseModuleToDamageByDiceRequest:
    """
    Используется для карточки действия
    "Киньте кубик. Нанесите любому модулю соперника (кроме командного) 1 урон при выпадении ≤4, а иначе - 2 урона".
    :param player: 
    :param damage: Количество урона, который нужно нанести (зависит от броска кубика)
    :return: Сконструированное действие
    """

    return ChooseModuleToDamageByDiceRequest(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="chooseModuleToDamageByDiceRequest",
        payload=ChooseModuleToDamageByDiceRequestPayload(player, damage)
    )


@dataclass
class ChooseModuleToDamageByDiceResponsePayload:
    info: ChooseModuleToDamageByDiceResponseInfo | None


@dataclass
class ChooseModuleToDamageByDiceResponse:
    uuid: str
    time: int
    type: Literal["chooseModuleToDamageByDiceResponse"]
    payload: ChooseModuleToDamageByDiceResponsePayload


def chooseModuleToDamageByDiceResponse(info: ChooseModuleToDamageByDiceResponseInfo | None) \
        -> ChooseModuleToDamageByDiceResponse:
    """
    :param info: Информация о модуле, по которому нужно нанести урон.
                 victimId - id игрока, victimModulePosition - позиция модуля на его корабле, по которому нужно ударить.
                 Если игрок не хочет наносить урон, то это поле остаётся пустым.
    :return: Сконструированное действие
    """

    return ChooseModuleToDamageByDiceResponse(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="chooseModuleToDamageByDiceResponse",
        payload=ChooseModuleToDamageByDiceResponsePayload(info)
    )


@dataclass
class ChoosePlayerToStealCardRequestPayload:
    player: PlayerId
    options: list[PlayerId]


@dataclass
class ChoosePlayerToStealCardRequest:
    uuid: str
    time: int
    type: Literal["choosePlayerToStealCardRequest"]
    payload: ChoosePlayerToStealCardRequestPayload


def choosePlayerToStealCardRequest(player: PlayerId, options: list[PlayerId]) \
        -> ChoosePlayerToStealCardRequest:
    """
    Используется для карточки действия
    "Выберите любого игрока, у которого на руках есть карточки. Посмотрите его карты и возьмите себе одну из них на ваш выбор".
    Это действие запрашивает игрока, у которого нужно своровать карточку
    :param player: 
    :param options: Список id игроков, у которых можно украсть карту.
    :return: Сконструированное действие
    """

    return ChoosePlayerToStealCardRequest(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="choosePlayerToStealCardRequest",
        payload=ChoosePlayerToStealCardRequestPayload(player, options)
    )


@dataclass
class ChoosePlayerToStealCardResponsePayload:
    target: PlayerId


@dataclass
class ChoosePlayerToStealCardResponse:
    uuid: str
    time: int
    type: Literal["choosePlayerToStealCardResponse"]
    payload: ChoosePlayerToStealCardResponsePayload


def choosePlayerToStealCardResponse(target: PlayerId) \
        -> ChoosePlayerToStealCardResponse:
    """
    :param target: id игрока, у которого нужно будет своровать карту. 
                   Этот id должен содержаться в списке choosePlayerToStealCardRequest::options
    :return: Сконструированное действие
    """

    return ChoosePlayerToStealCardResponse(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="choosePlayerToStealCardResponse",
        payload=ChoosePlayerToStealCardResponsePayload(target)
    )


@dataclass
class ChooseCardToStealRequestPayload:
    player: PlayerId
    cards: list[Card]


@dataclass
class ChooseCardToStealRequest:
    uuid: str
    time: int
    type: Literal["chooseCardToStealRequest"]
    payload: ChooseCardToStealRequestPayload


def chooseCardToStealRequest(player: PlayerId, cards: list[Card]) \
        -> ChooseCardToStealRequest:
    """
    Используется для карточки действия
    "Выберите любого игрока, у которого на руках есть карточки. Посмотрите его карты и возьмите себе одну из них на ваш выбор".
    Сначала с помощью choosePlayerToStealCardRequest запрашивается id игрока, у которого надо украсть карточку.
    Затем с помощью этого действия запрашивается карточка, которую нужно украсть.
    :param player: 
    :param cards: Список карт, которые можно украсть
    :return: Сконструированное действие
    """

    return ChooseCardToStealRequest(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="chooseCardToStealRequest",
        payload=ChooseCardToStealRequestPayload(player, cards)
    )


@dataclass
class ChooseCardToStealResponsePayload:
    chosenCardIndex: int


@dataclass
class ChooseCardToStealResponse:
    uuid: str
    time: int
    type: Literal["chooseCardToStealResponse"]
    payload: ChooseCardToStealResponsePayload


def chooseCardToStealResponse(chosenCardIndex: int) \
        -> ChooseCardToStealResponse:
    """
    :param chosenCardIndex: Индекс карты из chooseCardToStealRequest::cards, которую нужно украсть
    :return: Сконструированное действие
    """

    return ChooseCardToStealResponse(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="chooseCardToStealResponse",
        payload=ChooseCardToStealResponsePayload(chosenCardIndex)
    )


@dataclass
class UseEventCardToDealDamageRequestPayload:
    player: PlayerId


@dataclass
class UseEventCardToDealDamageRequest:
    uuid: str
    time: int
    type: Literal["useEventCardToDealDamageRequest"]
    payload: UseEventCardToDealDamageRequestPayload


def useEventCardToDealDamageRequest(player: PlayerId) \
        -> UseEventCardToDealDamageRequest:
    """
    Используется для карточки действия
    "Сохраните эту кар у себя на руке. В свой бой вы можете скинуть её, нанося 1 урон любому модулю корабля соперника (кроме командного)".
    :param player: 
    :return: Сконструированное действие
    """

    return UseEventCardToDealDamageRequest(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="useEventCardToDealDamageRequest",
        payload=UseEventCardToDealDamageRequestPayload(player)
    )


@dataclass
class UseEventCardToDealDamageResponsePayload:
    useEventCard: bool


@dataclass
class UseEventCardToDealDamageResponse:
    uuid: str
    time: int
    type: Literal["useEventCardToDealDamageResponse"]
    payload: UseEventCardToDealDamageResponsePayload


def useEventCardToDealDamageResponse(useEventCard: bool) \
        -> UseEventCardToDealDamageResponse:
    """
    :param useEventCard: Хочет ли игрок использовать карточку действия с руки, чтобы нанести урон сопернику.
    :return: Сконструированное действие
    """

    return UseEventCardToDealDamageResponse(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="useEventCardToDealDamageResponse",
        payload=UseEventCardToDealDamageResponsePayload(useEventCard)
    )


@dataclass
class ChooseModuleToDamageByEventCardRequestPayload:
    player: PlayerId
    victim: PlayerId


@dataclass
class ChooseModuleToDamageByEventCardRequest:
    uuid: str
    time: int
    type: Literal["chooseModuleToDamageByEventCardRequest"]
    payload: ChooseModuleToDamageByEventCardRequestPayload


def chooseModuleToDamageByEventCardRequest(player: PlayerId, victim: PlayerId) \
        -> ChooseModuleToDamageByEventCardRequest:
    """
    Используется для карточки действия
    "Сохраните эту кар у себя на руке. В свой бой вы можете скинуть её, нанося 1 урон любому модулю корабля соперника (кроме командного)".
    Сначала у пользователя запрашивается, хочет ли он воспользоваться этой карточкой, с помощью действия useEventCardToDealDamageRequest.
    Затем с помощью этого действия запрашивается модуль, по которому нужно ударить.
    :param player: 
    :param victim: id игрока, по модулю которого нужно нанести урон.
    :return: Сконструированное действие
    """

    return ChooseModuleToDamageByEventCardRequest(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="chooseModuleToDamageByEventCardRequest",
        payload=ChooseModuleToDamageByEventCardRequestPayload(player, victim)
    )


@dataclass
class ChooseModuleToDamageByEventCardResponsePayload:
    position: Vector2


@dataclass
class ChooseModuleToDamageByEventCardResponse:
    uuid: str
    time: int
    type: Literal["chooseModuleToDamageByEventCardResponse"]
    payload: ChooseModuleToDamageByEventCardResponsePayload


def chooseModuleToDamageByEventCardResponse(position: Vector2) \
        -> ChooseModuleToDamageByEventCardResponse:
    """
    :param position: Позиция модуля на корабле игрока chooseModuleToDamageByEventCardRequest::victim, по которому нужно нанести урон.
    :return: Сконструированное действие
    """

    return ChooseModuleToDamageByEventCardResponse(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="chooseModuleToDamageByEventCardResponse",
        payload=ChooseModuleToDamageByEventCardResponsePayload(position)
    )


@dataclass
class TryToRunawayRequestPayload:
    player: PlayerId
    type: RunawayType


@dataclass
class TryToRunawayRequest:
    uuid: str
    time: int
    type: Literal["tryToRunawayRequest"]
    payload: TryToRunawayRequestPayload


def tryToRunawayRequest(player: PlayerId, type: RunawayType) \
        -> TryToRunawayRequest:
    """
    Используется в бою, чтобы узнать, будет ли игрок пытаться сбежать.
    Он может это сделать двумя способами:
    Dice - с помощью кубика - тогда он сбегает или нет в зависимости от кубика
    MainModule - с помощью командного модуля - тогда он гарантированно сбегает
    :param player: 
    :param type: Способ сбегания: кубик или командный модуль
    :return: Сконструированное действие
    """

    return TryToRunawayRequest(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="tryToRunawayRequest",
        payload=TryToRunawayRequestPayload(player, type)
    )


@dataclass
class TryToRunawayResponsePayload:
    willRunaway: bool


@dataclass
class TryToRunawayResponse:
    uuid: str
    time: int
    type: Literal["tryToRunawayResponse"]
    payload: TryToRunawayResponsePayload


def tryToRunawayResponse(willRunaway: bool) \
        -> TryToRunawayResponse:
    """
    :param willRunaway: Хочет ли игрок попытаться сбежать
    :return: Сконструированное действие
    """

    return TryToRunawayResponse(
        uuid=str(uuid.uuid4()),
        time=int(time.time()),
        type="tryToRunawayResponse",
        payload=TryToRunawayResponsePayload(willRunaway)
    )
