"""
This file is autogenerated using server/src/tools/codegen/Codegen.ts tool.
Do not change it by hand! Instead, rerun generation script.
"""

import dataclasses
from abc import ABC, abstractmethod
from typing import Any

import socketio
from pydantic import TypeAdapter

from core.actions import *

from core.types import *


class BaseClient(ABC):

    def registerListeners(self, sio_client: socketio.AsyncClient):
        sio_client.on('choosePlayerForAttackRequest', self._on_choosePlayerForAttackRequest)
        sio_client.on('rebuildSpaceshipRequest', self._on_rebuildSpaceshipRequest)
        sio_client.on('chooseCardTypeRequest', self._on_chooseCardTypeRequest)
        sio_client.on('showCardsToPlayersRequest', self._on_showCardsToPlayersRequest)
        sio_client.on('drawAdditionalModuleCardRequest', self._on_drawAdditionalModuleCardRequest)
        sio_client.on('drawAnotherEventCardRequest', self._on_drawAnotherEventCardRequest)
        sio_client.on('discardCardsRequest', self._on_discardCardsRequest)
        sio_client.on('chooseProtectorRequest', self._on_chooseProtectorRequest)
        sio_client.on('chooseWeaponAndTargetRequest', self._on_chooseWeaponAndTargetRequest)
        sio_client.on('useModuleSecondTimeRequest', self._on_useModuleSecondTimeRequest)
        sio_client.on('chooseTargetRequest', self._on_chooseTargetRequest)
        sio_client.on('chooseModuleToRepairRequest', self._on_chooseModuleToRepairRequest)
        sio_client.on('permuteTopThreeEventCardsRequest', self._on_permuteTopThreeEventCardsRequest)
        sio_client.on('chooseModuleToDestroyRequest', self._on_chooseModuleToDestroyRequest)
        sio_client.on('chooseCardsForRepairSpaceshipRequest', self._on_chooseCardsForRepairSpaceshipRequest)
        sio_client.on('chooseModulesToRepairByDiscardedCardsRequest', self._on_chooseModulesToRepairByDiscardedCardsRequest)
        sio_client.on('chooseSolarPanelsToDestroyRequest', self._on_chooseSolarPanelsToDestroyRequest)
        sio_client.on('chooseModuleToRepairByDiceRequest', self._on_chooseModuleToRepairByDiceRequest)
        sio_client.on('chooseCardsToDiscardAndTakeAnotherRequest', self._on_chooseCardsToDiscardAndTakeAnotherRequest)
        sio_client.on('chooseModuleToMoveDamageRequest', self._on_chooseModuleToMoveDamageRequest)
        sio_client.on('chooseModuleToDamageByDiceRequest', self._on_chooseModuleToDamageByDiceRequest)
        sio_client.on('choosePlayerToStealCardRequest', self._on_choosePlayerToStealCardRequest)
        sio_client.on('chooseCardToStealRequest', self._on_chooseCardToStealRequest)
        sio_client.on('useEventCardToDealDamageRequest', self._on_useEventCardToDealDamageRequest)
        sio_client.on('chooseModuleToDamageByEventCardRequest', self._on_chooseModuleToDamageByEventCardRequest)
        sio_client.on('tryToRunawayRequest', self._on_tryToRunawayRequest)

    def on_action(self, type: str, payload: Any):
        """
        Вызывается при получении любого действия.
        Например, если приходит действие 'rebuildSpaceshipRequest', то:
        1. Вызывается этот метод с type='rebuildSpaceshipRequest' и со всем содержимым действия в payload.
        При этом payload - это dict, который получается после стандартной расшифровки JSON.
        2. Содержимое payload валидируется и переделывается в правильные типы данных.
        3. Вызывается 'self.rebuildSpaceshipRequest'
        """
        pass

    def _on_choosePlayerForAttackRequest(self, payload: Any) -> dict:
        print("📨 choosePlayerForAttackRequest")

        self.on_action("choosePlayerForAttackRequest", payload)

        decoded = TypeAdapter(ChoosePlayerForAttackRequestPayload).validate_python(payload)
        result = dataclasses.asdict(self.choosePlayerForAttackRequest(**dataclasses.asdict(decoded)))

        # remove all properties that are None
        result["payload"] = {k: v for k, v in result["payload"].items() if v is not None}

        return result

    def _on_rebuildSpaceshipRequest(self, payload: Any) -> dict:
        print("📨 rebuildSpaceshipRequest")

        self.on_action("rebuildSpaceshipRequest", payload)

        decoded = TypeAdapter(RebuildSpaceshipRequestPayload).validate_python(payload)
        result = dataclasses.asdict(self.rebuildSpaceshipRequest(**dataclasses.asdict(decoded)))

        # remove all properties that are None
        result["payload"] = {k: v for k, v in result["payload"].items() if v is not None}

        return result

    def _on_chooseCardTypeRequest(self, payload: Any) -> dict:
        print("📨 chooseCardTypeRequest")

        self.on_action("chooseCardTypeRequest", payload)

        decoded = TypeAdapter(ChooseCardTypeRequestPayload).validate_python(payload)
        result = dataclasses.asdict(self.chooseCardTypeRequest(**dataclasses.asdict(decoded)))

        # remove all properties that are None
        result["payload"] = {k: v for k, v in result["payload"].items() if v is not None}

        return result

    def _on_showCardsToPlayersRequest(self, payload: Any) -> dict:
        print("📨 showCardsToPlayersRequest")

        self.on_action("showCardsToPlayersRequest", payload)

        decoded = TypeAdapter(ShowCardsToPlayersRequestPayload).validate_python(payload)
        result = dataclasses.asdict(self.showCardsToPlayersRequest(**dataclasses.asdict(decoded)))

        # remove all properties that are None
        result["payload"] = {k: v for k, v in result["payload"].items() if v is not None}

        return result

    def _on_drawAdditionalModuleCardRequest(self, payload: Any) -> dict:
        print("📨 drawAdditionalModuleCardRequest")

        self.on_action("drawAdditionalModuleCardRequest", payload)

        decoded = TypeAdapter(DrawAdditionalModuleCardRequestPayload).validate_python(payload)
        result = dataclasses.asdict(self.drawAdditionalModuleCardRequest(**dataclasses.asdict(decoded)))

        # remove all properties that are None
        result["payload"] = {k: v for k, v in result["payload"].items() if v is not None}

        return result

    def _on_drawAnotherEventCardRequest(self, payload: Any) -> dict:
        print("📨 drawAnotherEventCardRequest")

        self.on_action("drawAnotherEventCardRequest", payload)

        decoded = TypeAdapter(DrawAnotherEventCardRequestPayload).validate_python(payload)
        result = dataclasses.asdict(self.drawAnotherEventCardRequest(**dataclasses.asdict(decoded)))

        # remove all properties that are None
        result["payload"] = {k: v for k, v in result["payload"].items() if v is not None}

        return result

    def _on_discardCardsRequest(self, payload: Any) -> dict:
        print("📨 discardCardsRequest")

        self.on_action("discardCardsRequest", payload)

        decoded = TypeAdapter(DiscardCardsRequestPayload).validate_python(payload)
        result = dataclasses.asdict(self.discardCardsRequest(**dataclasses.asdict(decoded)))

        # remove all properties that are None
        result["payload"] = {k: v for k, v in result["payload"].items() if v is not None}

        return result

    def _on_chooseProtectorRequest(self, payload: Any) -> dict:
        print("📨 chooseProtectorRequest")

        self.on_action("chooseProtectorRequest", payload)

        decoded = TypeAdapter(ChooseProtectorRequestPayload).validate_python(payload)
        result = dataclasses.asdict(self.chooseProtectorRequest(**dataclasses.asdict(decoded)))

        # remove all properties that are None
        result["payload"] = {k: v for k, v in result["payload"].items() if v is not None}

        return result

    def _on_chooseWeaponAndTargetRequest(self, payload: Any) -> dict:
        print("📨 chooseWeaponAndTargetRequest")

        self.on_action("chooseWeaponAndTargetRequest", payload)

        decoded = TypeAdapter(ChooseWeaponAndTargetRequestPayload).validate_python(payload)
        result = dataclasses.asdict(self.chooseWeaponAndTargetRequest(**dataclasses.asdict(decoded)))

        # remove all properties that are None
        result["payload"] = {k: v for k, v in result["payload"].items() if v is not None}

        return result

    def _on_useModuleSecondTimeRequest(self, payload: Any) -> dict:
        print("📨 useModuleSecondTimeRequest")

        self.on_action("useModuleSecondTimeRequest", payload)

        decoded = TypeAdapter(UseModuleSecondTimeRequestPayload).validate_python(payload)
        result = dataclasses.asdict(self.useModuleSecondTimeRequest(**dataclasses.asdict(decoded)))

        # remove all properties that are None
        result["payload"] = {k: v for k, v in result["payload"].items() if v is not None}

        return result

    def _on_chooseTargetRequest(self, payload: Any) -> dict:
        print("📨 chooseTargetRequest")

        self.on_action("chooseTargetRequest", payload)

        decoded = TypeAdapter(ChooseTargetRequestPayload).validate_python(payload)
        result = dataclasses.asdict(self.chooseTargetRequest(**dataclasses.asdict(decoded)))

        # remove all properties that are None
        result["payload"] = {k: v for k, v in result["payload"].items() if v is not None}

        return result

    def _on_chooseModuleToRepairRequest(self, payload: Any) -> dict:
        print("📨 chooseModuleToRepairRequest")

        self.on_action("chooseModuleToRepairRequest", payload)

        decoded = TypeAdapter(ChooseModuleToRepairRequestPayload).validate_python(payload)
        result = dataclasses.asdict(self.chooseModuleToRepairRequest(**dataclasses.asdict(decoded)))

        # remove all properties that are None
        result["payload"] = {k: v for k, v in result["payload"].items() if v is not None}

        return result

    def _on_permuteTopThreeEventCardsRequest(self, payload: Any) -> dict:
        print("📨 permuteTopThreeEventCardsRequest")

        self.on_action("permuteTopThreeEventCardsRequest", payload)

        decoded = TypeAdapter(PermuteTopThreeEventCardsRequestPayload).validate_python(payload)
        result = dataclasses.asdict(self.permuteTopThreeEventCardsRequest(**dataclasses.asdict(decoded)))

        # remove all properties that are None
        result["payload"] = {k: v for k, v in result["payload"].items() if v is not None}

        return result

    def _on_chooseModuleToDestroyRequest(self, payload: Any) -> dict:
        print("📨 chooseModuleToDestroyRequest")

        self.on_action("chooseModuleToDestroyRequest", payload)

        decoded = TypeAdapter(ChooseModuleToDestroyRequestPayload).validate_python(payload)
        result = dataclasses.asdict(self.chooseModuleToDestroyRequest(**dataclasses.asdict(decoded)))

        # remove all properties that are None
        result["payload"] = {k: v for k, v in result["payload"].items() if v is not None}

        return result

    def _on_chooseCardsForRepairSpaceshipRequest(self, payload: Any) -> dict:
        print("📨 chooseCardsForRepairSpaceshipRequest")

        self.on_action("chooseCardsForRepairSpaceshipRequest", payload)

        decoded = TypeAdapter(ChooseCardsForRepairSpaceshipRequestPayload).validate_python(payload)
        result = dataclasses.asdict(self.chooseCardsForRepairSpaceshipRequest(**dataclasses.asdict(decoded)))

        # remove all properties that are None
        result["payload"] = {k: v for k, v in result["payload"].items() if v is not None}

        return result

    def _on_chooseModulesToRepairByDiscardedCardsRequest(self, payload: Any) -> dict:
        print("📨 chooseModulesToRepairByDiscardedCardsRequest")

        self.on_action("chooseModulesToRepairByDiscardedCardsRequest", payload)

        decoded = TypeAdapter(ChooseModulesToRepairByDiscardedCardsRequestPayload).validate_python(payload)
        result = dataclasses.asdict(self.chooseModulesToRepairByDiscardedCardsRequest(**dataclasses.asdict(decoded)))

        # remove all properties that are None
        result["payload"] = {k: v for k, v in result["payload"].items() if v is not None}

        return result

    def _on_chooseSolarPanelsToDestroyRequest(self, payload: Any) -> dict:
        print("📨 chooseSolarPanelsToDestroyRequest")

        self.on_action("chooseSolarPanelsToDestroyRequest", payload)

        decoded = TypeAdapter(ChooseSolarPanelsToDestroyRequestPayload).validate_python(payload)
        result = dataclasses.asdict(self.chooseSolarPanelsToDestroyRequest(**dataclasses.asdict(decoded)))

        # remove all properties that are None
        result["payload"] = {k: v for k, v in result["payload"].items() if v is not None}

        return result

    def _on_chooseModuleToRepairByDiceRequest(self, payload: Any) -> dict:
        print("📨 chooseModuleToRepairByDiceRequest")

        self.on_action("chooseModuleToRepairByDiceRequest", payload)

        decoded = TypeAdapter(ChooseModuleToRepairByDiceRequestPayload).validate_python(payload)
        result = dataclasses.asdict(self.chooseModuleToRepairByDiceRequest(**dataclasses.asdict(decoded)))

        # remove all properties that are None
        result["payload"] = {k: v for k, v in result["payload"].items() if v is not None}

        return result

    def _on_chooseCardsToDiscardAndTakeAnotherRequest(self, payload: Any) -> dict:
        print("📨 chooseCardsToDiscardAndTakeAnotherRequest")

        self.on_action("chooseCardsToDiscardAndTakeAnotherRequest", payload)

        decoded = TypeAdapter(ChooseCardsToDiscardAndTakeAnotherRequestPayload).validate_python(payload)
        result = dataclasses.asdict(self.chooseCardsToDiscardAndTakeAnotherRequest(**dataclasses.asdict(decoded)))

        # remove all properties that are None
        result["payload"] = {k: v for k, v in result["payload"].items() if v is not None}

        return result

    def _on_chooseModuleToMoveDamageRequest(self, payload: Any) -> dict:
        print("📨 chooseModuleToMoveDamageRequest")

        self.on_action("chooseModuleToMoveDamageRequest", payload)

        decoded = TypeAdapter(ChooseModuleToMoveDamageRequestPayload).validate_python(payload)
        result = dataclasses.asdict(self.chooseModuleToMoveDamageRequest(**dataclasses.asdict(decoded)))

        # remove all properties that are None
        result["payload"] = {k: v for k, v in result["payload"].items() if v is not None}

        return result

    def _on_chooseModuleToDamageByDiceRequest(self, payload: Any) -> dict:
        print("📨 chooseModuleToDamageByDiceRequest")

        self.on_action("chooseModuleToDamageByDiceRequest", payload)

        decoded = TypeAdapter(ChooseModuleToDamageByDiceRequestPayload).validate_python(payload)
        result = dataclasses.asdict(self.chooseModuleToDamageByDiceRequest(**dataclasses.asdict(decoded)))

        # remove all properties that are None
        result["payload"] = {k: v for k, v in result["payload"].items() if v is not None}

        return result

    def _on_choosePlayerToStealCardRequest(self, payload: Any) -> dict:
        print("📨 choosePlayerToStealCardRequest")

        self.on_action("choosePlayerToStealCardRequest", payload)

        decoded = TypeAdapter(ChoosePlayerToStealCardRequestPayload).validate_python(payload)
        result = dataclasses.asdict(self.choosePlayerToStealCardRequest(**dataclasses.asdict(decoded)))

        # remove all properties that are None
        result["payload"] = {k: v for k, v in result["payload"].items() if v is not None}

        return result

    def _on_chooseCardToStealRequest(self, payload: Any) -> dict:
        print("📨 chooseCardToStealRequest")

        self.on_action("chooseCardToStealRequest", payload)

        decoded = TypeAdapter(ChooseCardToStealRequestPayload).validate_python(payload)
        result = dataclasses.asdict(self.chooseCardToStealRequest(**dataclasses.asdict(decoded)))

        # remove all properties that are None
        result["payload"] = {k: v for k, v in result["payload"].items() if v is not None}

        return result

    def _on_useEventCardToDealDamageRequest(self, payload: Any) -> dict:
        print("📨 useEventCardToDealDamageRequest")

        self.on_action("useEventCardToDealDamageRequest", payload)

        decoded = TypeAdapter(UseEventCardToDealDamageRequestPayload).validate_python(payload)
        result = dataclasses.asdict(self.useEventCardToDealDamageRequest(**dataclasses.asdict(decoded)))

        # remove all properties that are None
        result["payload"] = {k: v for k, v in result["payload"].items() if v is not None}

        return result

    def _on_chooseModuleToDamageByEventCardRequest(self, payload: Any) -> dict:
        print("📨 chooseModuleToDamageByEventCardRequest")

        self.on_action("chooseModuleToDamageByEventCardRequest", payload)

        decoded = TypeAdapter(ChooseModuleToDamageByEventCardRequestPayload).validate_python(payload)
        result = dataclasses.asdict(self.chooseModuleToDamageByEventCardRequest(**dataclasses.asdict(decoded)))

        # remove all properties that are None
        result["payload"] = {k: v for k, v in result["payload"].items() if v is not None}

        return result

    def _on_tryToRunawayRequest(self, payload: Any) -> dict:
        print("📨 tryToRunawayRequest")

        self.on_action("tryToRunawayRequest", payload)

        decoded = TypeAdapter(TryToRunawayRequestPayload).validate_python(payload)
        result = dataclasses.asdict(self.tryToRunawayRequest(**dataclasses.asdict(decoded)))

        # remove all properties that are None
        result["payload"] = {k: v for k, v in result["payload"].items() if v is not None}

        return result

    @abstractmethod
    def choosePlayerForAttackRequest(self, player: PlayerId, reason: AttackReason, required: bool) -> ChoosePlayerForAttackResponse:
        ...

    @abstractmethod
    def rebuildSpaceshipRequest(self, player: PlayerId) -> RebuildSpaceshipResponse:
        ...

    @abstractmethod
    def chooseCardTypeRequest(self, player: PlayerId) -> ChooseCardTypeResponse:
        ...

    @abstractmethod
    def showCardsToPlayersRequest(self, player: PlayerId, cardsReceiver: PlayerId, cards: list[Card]) -> ShowCardsToPlayersResponse:
        ...

    @abstractmethod
    def drawAdditionalModuleCardRequest(self, player: PlayerId) -> DrawAdditionalModuleCardResponse:
        ...

    @abstractmethod
    def drawAnotherEventCardRequest(self, player: PlayerId) -> DrawAnotherEventCardResponse:
        ...

    @abstractmethod
    def discardCardsRequest(self, player: PlayerId) -> DiscardCardsResponse:
        ...

    @abstractmethod
    def chooseProtectorRequest(self, player: PlayerId) -> ChooseProtectorResponse:
        ...

    @abstractmethod
    def chooseWeaponAndTargetRequest(self, player: PlayerId, victim: PlayerId) -> ChooseWeaponAndTargetResponse:
        ...

    @abstractmethod
    def useModuleSecondTimeRequest(self, player: PlayerId, moduleType: ModuleType) -> UseModuleSecondTimeResponse:
        ...

    @abstractmethod
    def chooseTargetRequest(self, player: PlayerId, victim: PlayerId) -> ChooseTargetResponse:
        ...

    @abstractmethod
    def chooseModuleToRepairRequest(self, player: PlayerId) -> ChooseModuleToRepairResponse:
        ...

    @abstractmethod
    def permuteTopThreeEventCardsRequest(self, player: PlayerId, cards: list[EventCard]) -> PermuteTopThreeEventCardsResponse:
        ...

    @abstractmethod
    def chooseModuleToDestroyRequest(self, player: PlayerId) -> ChooseModuleToDestroyResponse:
        ...

    @abstractmethod
    def chooseCardsForRepairSpaceshipRequest(self, player: PlayerId) -> ChooseCardsForRepairSpaceshipResponse:
        ...

    @abstractmethod
    def chooseModulesToRepairByDiscardedCardsRequest(self, player: PlayerId, count: int) -> ChooseModulesToRepairByDiscardedCardsResponse:
        ...

    @abstractmethod
    def chooseSolarPanelsToDestroyRequest(self, player: PlayerId, count: int) -> ChooseSolarPanelsToDestroyResponse:
        ...

    @abstractmethod
    def chooseModuleToRepairByDiceRequest(self, player: PlayerId, amount: int) -> ChooseModuleToRepairByDiceResponse:
        ...

    @abstractmethod
    def chooseCardsToDiscardAndTakeAnotherRequest(self, player: PlayerId) -> ChooseCardsToDiscardAndTakeAnotherResponse:
        ...

    @abstractmethod
    def chooseModuleToMoveDamageRequest(self, player: PlayerId, reason: MoveDamageReason) -> ChooseModuleToMoveDamageResponse:
        ...

    @abstractmethod
    def chooseModuleToDamageByDiceRequest(self, player: PlayerId, damage: int) -> ChooseModuleToDamageByDiceResponse:
        ...

    @abstractmethod
    def choosePlayerToStealCardRequest(self, player: PlayerId, options: list[PlayerId]) -> ChoosePlayerToStealCardResponse:
        ...

    @abstractmethod
    def chooseCardToStealRequest(self, player: PlayerId, cards: list[Card]) -> ChooseCardToStealResponse:
        ...

    @abstractmethod
    def useEventCardToDealDamageRequest(self, player: PlayerId) -> UseEventCardToDealDamageResponse:
        ...

    @abstractmethod
    def chooseModuleToDamageByEventCardRequest(self, player: PlayerId, victim: PlayerId) -> ChooseModuleToDamageByEventCardResponse:
        ...

    @abstractmethod
    def tryToRunawayRequest(self, player: PlayerId, type: RunawayType) -> TryToRunawayResponse:
        ...

