"""
This file is autogenerated using server/src/tools/codegen/Codegen.ts tool.
Do not change it by hand! Instead, rerun generation script.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Any, Literal

PlayerId = int

ModuleId = int


@dataclass
class Vector2:
    x: int
    y: int


class ModuleType(str, Enum):
    MainModule = "MainModule"
    SpaceSolver = "SpaceSolver"
    IonDestroyer = "IonDestroyer"
    QuantumDestabilizer = "QuantumDestabilizer"
    SolarPanel = "SolarPanel"
    NuclearReactor = "NuclearReactor"
    DarkMatterGenerator = "DarkMatterGenerator"
    SmallBattery = "SmallBattery"
    Battery = "Battery"
    SmallQuantumProtector = "SmallQuantumProtector"
    QuantumProtector = "QuantumProtector"
    AttackModule = "AttackModule"
    RepairModule = "RepairModule"
    StructureModule = "StructureModule"


class EventType(str, Enum):
    PutTopThreeCardsInAnyOrder = "PutTopThreeCardsInAnyOrder"
    PutTopThreeCardsInAnyOrderAndTakeTop = "PutTopThreeCardsInAnyOrderAndTakeTop"
    TakeOneBuildingCard = "TakeOneBuildingCard"
    TakeTwoBuildingCards = "TakeTwoBuildingCards"
    LooseFiveEnergy = "LooseFiveEnergy"
    TakeFiveEnergy = "TakeFiveEnergy"
    SkipNextTurn = "SkipNextTurn"
    LooseAllYourCards = "LooseAllYourCards"
    DestroyAnyModuleOnYourSpaceship = "DestroyAnyModuleOnYourSpaceship"
    DestroyTwoSolarPanelsOnYourSpaceship = "DestroyTwoSolarPanelsOnYourSpaceship"
    AttackRight = "AttackRight"
    AttackLeft = "AttackLeft"
    AttackNextToRight = "AttackNextToRight"
    AttackNextToLeft = "AttackNextToLeft"
    AttackAny = "AttackAny"
    TossDiceAndTakeBuildingCards = "TossDiceAndTakeBuildingCards"
    TossDiceAndDealDamage = "TossDiceAndDealDamage"
    TossDiceAndGetEnergy = "TossDiceAndGetEnergy"
    TossDiceAndRepairYourModule = "TossDiceAndRepairYourModule"
    SaveCardAndThenAttack = "SaveCardAndThenAttack"
    SaveCardAndThenDealDamage = "SaveCardAndThenDealDamage"
    ChoosePlayerAndStealHisCard = "ChoosePlayerAndStealHisCard"
    DiscardCardAndRepairSpaceship = "DiscardCardAndRepairSpaceship"
    MoveDamage = "MoveDamage"
    DiscardCardsAndTakeBuildingCards = "DiscardCardsAndTakeBuildingCards"


class MainModuleType(str, Enum):
    DrawAnotherEventCard = "DrawAnotherEventCard"
    DrawAdditionalModuleCard = "DrawAdditionalModuleCard"
    MoveDamage = "MoveDamage"
    UseModuleSecondTime = "UseModuleSecondTime"
    AttackOrRunaway = "AttackOrRunaway"


@dataclass
class ModuleConnectors:
    top: int
    right: int
    bottom: int
    left: int


@dataclass
class ModuleCard:
    id: ModuleId
    name: str
    connectors: ModuleConnectors
    strength: int
    capacity: int
    energyCost: int
    energyIncrease: int
    type: ModuleType
    totalHealth: int
    health: int
    x: int
    y: int
    rotation: int
    mainModuleType: MainModuleType | None = None


@dataclass
class EventCard:
    id: ModuleId
    type: EventType
    description: str


@dataclass
class CardModule:
    module: ModuleCard
    cardType: Literal["module"]


@dataclass
class CardEvent:
    event: EventCard
    cardType: Literal["event"]


Card = CardModule | CardEvent


class CardType(str, Enum):
    Module = "Module"
    Event = "Event"


@dataclass
class TimeControlSettings:
    startTime: int
    defaultTimeIncrease: int
    fightTimeIncrease: int
    loseWhenTimeout: bool


@dataclass
class GameSettings:
    seed: str
    isPublic: bool
    isDebug: bool
    startCardsCount: int
    mainModuleRunawayEnergyCost: int
    energyToAttackByMainModule: int
    energyToMoveDamageByMainModule: int
    damageMovedByMainModule: int
    energyToDragAnotherEventCardByMainModule: int
    energyToDragAdditionalCardByMainModule: int
    maxCardsOnHand: int
    diceResultToRunaway: int
    timeControlSettings: TimeControlSettings | None = None


@dataclass
class FightState:
    first: PlayerId
    second: PlayerId
    isFirstPlayerTurn: bool
    isFightEnded: bool


class TimeRecordType(str, Enum):
    DEFAULT_TURN_STARTED = "DEFAULT_TURN_STARTED"
    DEFAULT_TURN_ENDED = "DEFAULT_TURN_ENDED"
    DEFAULT_TURN_INTERRUPTED = "DEFAULT_TURN_INTERRUPTED"
    DEFAULT_TURN_CONTINUED = "DEFAULT_TURN_CONTINUED"
    FIGHT_TURN_STARTED = "FIGHT_TURN_STARTED"
    FIGHT_TURN_ENDED = "FIGHT_TURN_ENDED"
    PAUSE_STARTED = "PAUSE_STARTED"
    PAUSE_ENDED = "PAUSE_ENDED"


@dataclass
class TimeRecord:
    type: TimeRecordType
    playerId: PlayerId
    time: int


@dataclass
class Spaceship:
    modules: list[ModuleCard]
    activatedProtector: Vector2 | None = None


@dataclass
class Player:
    id: PlayerId
    name: str
    spaceship: Spaceship
    hand: list[Card]
    energy: int
    skipNextTurn: bool
    usedModuleSecondTimeOnThisTurn: bool
    lose: bool
    time: int


@dataclass
class GameStateStack:
    module: list[ModuleCard]
    event: list[EventCard]


@dataclass
class GameStateDiscards:
    module: list[ModuleCard]
    event: list[EventCard]


@dataclass
class GameState:
    stack: GameStateStack
    discards: GameStateDiscards
    mainModulesStack: list[ModuleCard]
    players: list[Player]
    currentPlayerId: PlayerId
    settings: GameSettings
    timeRecords: list[TimeRecord]
    fight: FightState | None = None


@dataclass
class Message:
    text: str
    payload: Any | None = None


@dataclass
class OtherPlayer:
    id: PlayerId
    name: str
    energy: int
    spaceship: Spaceship
    handSize: int
    lose: bool


@dataclass
class GameForPlayerDTOOnlineMapElements:
    player: PlayerId
    online: bool


@dataclass
class GameForPlayerDTOTimeControlPlayersTimeElements:
    player: PlayerId
    time: int


@dataclass
class GameForPlayerDTOTimeControl:
    playersTime: list[GameForPlayerDTOTimeControlPlayersTimeElements]
    timeDecreasingPlayerId: PlayerId | None = None


@dataclass
class GameForPlayerDTO:
    isPaused: bool
    currentTurnPlayerId: PlayerId
    settings: GameSettings
    player: Player
    otherPlayers: list[OtherPlayer]
    onlineMap: list[GameForPlayerDTOOnlineMapElements]
    messages: list[Message]
    timeControl: GameForPlayerDTOTimeControl | None = None


class MoveDamageReason(str, Enum):
    MainModule = "MainModule"
    EventCard = "EventCard"


class RunawayType(str, Enum):
    Dice = "Dice"
    MainModule = "MainModule"


class AttackReason(str, Enum):
    MainModule = "MainModule"
    AttackModule = "AttackModule"
    AttackAnyEventCard = "AttackAnyEventCard"
    AttackLaterEventCard = "AttackLaterEventCard"
    UsingAttackModuleSecondTime = "UsingAttackModuleSecondTime"


class CardDestination(str, Enum):
    hand = "hand"
    discard = "discard"


@dataclass
class RebuildSpaceshipResponseNewSpaceshipElements:
    id: ModuleId
    position: Vector2
    rotation: int


@dataclass
class ChooseModuleToMoveDamageResponseMove:
    source: Vector2
    destination: Vector2


@dataclass
class ChooseModuleToDamageByDiceResponseInfo:
    victimId: PlayerId
    victimModulePosition: Vector2
