name: Docker Compose Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker/compose:debian-1.29.2
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker images
        run: |
          docker compose -f compose.yml build
      - name: Run Docker-compose
        run: |
          docker compose -f compose.yml up -d
          docker compose -f compose.yml ps
          sleep 60
      - name: Test Node.js service with curl
        run: |
          SERVICE_URL="http://localhost:3000"
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$SERVICE_URL")
          
          if [ "$HTTP_STATUS" -eq 200 ]; then
            echo "Test Passed: Service returned HTTP 200 OK."
            exit 0
          else
            echo "Test Failed: Service did not return HTTP 200."
            echo "Actual HTTP status: $HTTP_STATUS"
            exit 1
          fi
      - name: Stop and remove containers
        run: docker compose -f compose.yml down